force-app/main/default/objects/AI_Cross_Object_Filter__c/AI_Cross_Object_Filter__c.object-meta.xml
<CustomObject>
    <label>Cross Object Filter</label>
    <nameField>
        <displayFormat>CF-{00000}</displayFormat>
        <label>Filter #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Object Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Cross_Object_Filter__c/fields/AI_Prompt_Scheduler__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt_Scheduler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Scheduler</label>
    <referenceTo>AI_Prompt_Scheduler__c</referenceTo>
    <relationshipLabel>Cross Object Filters</relationshipLabel>
    <relationshipName>Cross_Object_Filters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Specify the target object for the prompt.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Only prompts with &apos;Active&apos; status will be available to End User. Ensure to Activate the prompt</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Visibility_Condition__c.field-meta.xml
<CustomField>
    <fullName>Visibility_Condition__c</fullName>
    <label>Visibility Condition</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/AI_Prompt_Scheduler__c.object-meta.xml
<CustomObject>
    <label>Prompt Scheduler</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Scheduler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/AI_Scheduler__c.field-meta.xml
<CustomField>
    <fullName>AI_Scheduler__c</fullName>
    <label>AI Mass Processing</label>
    <referenceTo>AI_Scheduler__c</referenceTo>
    <relationshipLabel>Prompt Scheduler</relationshipLabel>
    <relationshipName>Prompt_Scheduler</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/Cross_Object_Filter_Condition__c.field-meta.xml
<CustomField>
    <fullName>Cross_Object_Filter_Condition__c</fullName>
    <label>Cross Object Filter Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AI_Prompt__c.Type__c</field>
            <operation>notEqual</operation>
            <value>Custom</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>Prompt Scheduler</relationshipLabel>
    <relationshipName>Prompt_Scheduler</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/Record_Limit__c.field-meta.xml
<CustomField>
    <fullName>Record_Limit__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Record Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/Where_Clause__c.field-meta.xml
<CustomField>
    <fullName>Where_Clause__c</fullName>
    <label>Where Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/AI_Response__c.object-meta.xml
<CustomObject>
    <label>Security Audit</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Audit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Response__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Prompt that is used</inlineHelpText>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipName>AI_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Scheduled_Run__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Run</label>
    <referenceTo>AI_Scheduled_Run__c</referenceTo>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Data Extracted</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Errored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Scheduled_Run__c/AI_Scheduled_Run__c.object-meta.xml
<CustomObject>
    <label>Scheduled Run</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Run #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Scheduled_Run__c/fields/Scheduler__c.field-meta.xml
<CustomField>
    <fullName>Scheduler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduler</label>
    <referenceTo>AI_Scheduler__c</referenceTo>
    <relationshipLabel>Scheduled Runs</relationshipLabel>
    <relationshipName>Scheduled_Runs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Scheduled_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Errored</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Scheduler__c/AI_Scheduler__c.object-meta.xml
<CustomObject>
    <label>AI Mass Processing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Mass Processing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Scheduler__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AIPromptRetryBatch.cls
/**
* @description       : 
* @author            : Rishabh Goel
* @group             : Plumcloud Labs
* @last modified on  : 07-13-2023
* @last modified by  : Rishabh Goel
**/
public with sharing class AIPromptRetryBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
	
    public AI_Scheduled_Run__c schRun;
    public AI_Prompt_Scheduler__c sch;
    public AI_Prompt__c aiPrompt;
    
    /**
     * Constructs a new instance of the AIPromptRetryBatch class.
     *
     * This constructor is used to create a batch job for retrying AI prompts,
     * based on the information provided in the AI_Scheduled_Run__c object.
     *
     * @param schRun The AI_Scheduled_Run__c object containing the information
     *               needed to configure the batch job for retrying AI prompts.
     */
    public AIPromptRetryBatch(AI_Scheduled_Run__c schRun, AI_Prompt_Scheduler__c sch){
        this.schRun = schRun;
        this.sch = sch;
    }
    
    /**
     * The start method is part of the Database.Batchable interface in Salesforce Apex.
     * It is called at the beginning of the batch job and is responsible for providing
     * the query locator that defines the scope of records to be processed in the batch.
     *
     * @param BC The Database.BatchableContext parameter provides access to the context
     *           information for the batch job.
     * @return Database.QueryLocator The query locator object that defines the set of
     *         records to be processed in the batch. This could be a SOQL query or a
     *         dynamic query locator.
     */
    public Database.QueryLocator start(Database.BatchableContext BC){
        sch = [SELECT Id, Cross_Object_Filter_Condition__c, Prompt__c FROM AI_Prompt_Scheduler__c WHERE Id=:sch.Id];
        aiPrompt = AIPromptSelector.getAIPromptById(sch.Prompt__c);
        
        return Database.getQueryLocator([
            SELECT Id, AI_Prompt__c, Record_Id__c
            FROM AI_Response__c 
            WHERE Scheduled_Run__c =:schRun.Id
            AND Status__c =:AIConstants.RESP_STATUS_ERROR
        ]);
    }
    
    /**
     * This method is part of a Salesforce Batch Apex class and is invoked to process a batch of AI_Response__c records.
     * It performs the actual processing logic on the provided batch of records.
     *
     * @param BC The context for the batch job, providing information about the execution environment.
     * @param scope A list of AI_Response__c records representing the batch of data to be processed.
     */
    public void execute(Database.BatchableContext BC, List<AI_Response__c> scope){
        /*for(AI_Response__c resp : scope){
            resp.Status__c = AIConstants.RESP_STATUS_DATA_EXT;
        }
        FLSCheck.getInstance().updateDML(scope);*/
        AI_Response__c resp = scope.get(0);
        resp = ChatGPTUtills.getDataUsingFiles(resp);
        resp.Id = scope.get(0).Id;
        try{ 
            
            Boolean isValid = true;
            String message;
            
            //checking visibility condition and record types for qualification of record.
            List<String> recordTypes = String.isNotBlank(aiPrompt.Record_Type__c) ? aiPrompt.Record_Type__c.split(';') : null;
            if(String.isNotBlank(aiPrompt.Visibility_Condition__c) || (recordTypes != null && !recordTypes.isEmpty())){
                isValid = GPTfyConsoleController.isValidVisibilityCondition(aiPrompt.Object__c, resp.Record_Id__c, aiPrompt.Visibility_Condition__c, recordTypes);
                message = !isValid ? 'Disqualified from Visibility Condition.' : '';
            }
            
            //checking cross object filter condition and record types for qualification of record.
            if(String.isNotBlank(sch.Cross_Object_Filter_Condition__c)){
                List<AI_Cross_Object_Filter__c> filters = AICrossObjectFilterService.getCrossObjectFilters(sch.Id);
                if(filters != null && !filters.isEmpty()){
                    Set<String> qualifiedIds = AICrossObjectFilterService.init(
                        sch.Cross_Object_Filter_Condition__c, 
                        filters, 
                        new Set<String>{resp.Record_Id__c}
                    );
                    if(qualifiedIds == null || qualifiedIds.isEmpty() || !qualifiedIds.contains(resp.Record_Id__c)){
                        isValid = false;
                        message = !isValid ? 'Disqualified from Cross Object Filters.' : '';
                    }
                }  
            }
            
            if(!isValid){
                resp.Status__c = AIConstants.RESP_STATUS_DISQ;
                resp.Message__c = message;
            }else{
                resp = ChatGPTUtills.getExtractedData(resp.Record_Id__c, aiPrompt, null, resp); 
            	resp.Status__c = AIConstants.RESP_STATUS_DATA_EXT;
            }
            FLSCheck.getInstance().updateDML(new List<AI_Response__c>{resp});
            ChatGPTUtills.rollupAIResponseScheduledRun(schRun.Id);
        }catch(Exception e){
            resp.Status__c = AIConstants.RESP_STATUS_ERROR;
            resp.Message__c = e.getMessage();
            FLSCheck.getInstance().updateDML(new List<AI_Response__c>{resp});
            ChatGPTUtills.rollupAIResponseScheduledRun(schRun.Id);
        }
    }
    
    /**
     * This method is called when the batch job finishes its execution.
     * It provides an opportunity to perform any cleanup or finalization tasks.
     *
     * @param BC The BatchableContext object, providing information about the batch job context.
     */
    public void finish(Database.BatchableContext BC){
        ChatGPTUtills.rollupAIResponseScheduledRun(schRun.Id);
        AI_Scheduled_Run__c scheduleRun = [SELECT Id, Status__c FROM AI_Scheduled_Run__c WHERE Id=:schRun.Id];
        if(scheduleRun.Status__c != AIConstants.SCH_STATUS_CANCELLED){
            for(AI_Prompt_Scheduler__c sc : [SELECT Id, Prompt__c, Where_Clause__c, Record_Limit__c,
                                             AI_Scheduler__c, AI_Scheduler__r.Retry_Count__c
                                             FROM AI_Prompt_Scheduler__c 
                                             WHERE AI_Scheduler__c =:schRun.Scheduler__c
                                             AND Prompt__r.Status__c = 'Active']){
                Database.executeBatch(new AIPromptProcessingBatch(sc, schRun), 1);
            }
        }
    }
}