force-app/main/default/objects/AI_Scheduled_Run__c/AI_Scheduled_Run__c.object-meta.xml
<CustomObject>
    <label>Scheduled Run</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Run #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Scheduled_Run__c/fields/Scheduler__c.field-meta.xml
<CustomField>
    <fullName>Scheduler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduler</label>
    <referenceTo>AI_Scheduler__c</referenceTo>
    <relationshipLabel>Scheduled Runs</relationshipLabel>
    <relationshipName>Scheduled_Runs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Scheduled_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Errored</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AIPromptAbortQueueable.cls
/**
* @description       : 
* @author            : Adarsh Sharma
* @group             : Plumcloud Labs
* @last modified on  : 11-05-2024
* @last modified by  : Adarsh Sharma
**/
public with sharing class AIPromptAbortQueueable implements Queueable {
    
    public String schRunId; 
    
    /**
     * Constructs a new AIPromptRequestBatch.
     * 
     * @param schRunId The AI Scheduled Run object representing the scheduled run for the prompt.
     * 
     * This constructor is used to initialize a batch processing job for Security Audit. It takes
     * a scheduled run object as parameters to set up the batch with
     * the necessary information for processing Security Audit.
     */
    public AIPromptAbortQueueable(String schRunId){
        this.schRunId = schRunId;
    }
    
    public void execute(QueueableContext context) {
        for(AsyncApexJob asyncJob : [SELECT Id, CronTriggerId FROM AsyncApexJob WHERE ApexClass.Name IN:AIConstants.SCH_BATCH_CLASSES AND Status!=:AIConstants.SCH_STATUS_ABORTED AND Status!=:AIConstants.SCH_STATUS_COMPLETED]){
            system.abortJob((asyncJob.CronTriggerId!=null?asyncJob.CronTriggerId:asyncJob.Id));
        }
        
        AI_Scheduled_Run__c schRun = [SELECT Id, Scheduler__c FROM AI_Scheduled_Run__c WHERE Id =:schRunId LIMIT 1];
        schRun.Status__c = AIConstants.SCH_STATUS_CANCELLED;
        FLSCheck.getInstance().updateDML(new List<AI_Scheduled_Run__c>{schRun});
        
        Database.executeBatch(new AIPromptAbortBatch(schRunId), 200);
    }
}