force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/Response_Validation_Condition__c.field-meta.xml
<CustomField>
    <fullName>Response_Validation_Condition__c</fullName>
    <label>Response Validation Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/AI_Prompt_Response_Validation__c.object-meta.xml
<CustomObject>
    <label>Prompt Response Validation</label>
    <nameField>
        <displayFormat>RV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Response Validations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>Excludes</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <label>Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>Prompt Response Validations</relationshipLabel>
    <relationshipName>Prompt_Response_Validations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AIResponseValidationUtility.cls
public with sharing class AIResponseValidationUtility {
	
    public static Boolean validateResponse(AI_Prompt__c pmt, String response){
        Boolean isValid = true;
        
        String responseCondition = '';
        if(String.isNotBlank(pmt.Response_Validation_Condition__c)){
            responseCondition = pmt.Response_Validation_Condition__c;
        }
        
        if(String.isNotBlank(response)){
            List<AI_Prompt_Response_Validation__c> lstOfValidations = [SELECT Id, Sequence__c, Action__c, Value__c 
                                                                       FROM AI_Prompt_Response_Validation__c
                                                                       WHERE AI_Prompt__c =:pmt.Id
                                                                       ORDER BY Sequence__c DESC];
            
            Map<String, Boolean> mapOfSequenceToValid = new Map<String, Boolean>();
            if(lstOfValidations != null && !lstOfValidations.isEmpty()){
                for(AI_Prompt_Response_Validation__c val : lstOfValidations){
                    Boolean iValid = checkValidityBasedOnAction(response, val);
                    String sequence = val.Sequence__c != null ? String.valueOf((Integer)val.Sequence__c) : '';
                    mapOfSequenceToValid.put(sequence, iValid);                                             
            	}

                List<Integer> integerSequences = new List<Integer>();
                for(String sequence : mapOfSequenceToValid.keySet()){
                    integerSequences.add(Integer.valueOf(sequence));
                }
                integerSequences.sort();
    
                if(String.isBlank(responseCondition)){
                    responseCondition = String.join(new List<String>(mapOfSequenceToValid.keySet()), ' AND ');
                }
    
                for(Integer i = integerSequences.size() - 1; i >= 0; i--){
                    String sequence = String.valueOf(integerSequences.get(i));
                    String val = mapOfSequenceToValid.get(sequence) ? 'true' : 'false';
                    while(responseCondition.contains(sequence)){
                        responseCondition = responseCondition.replaceFirst(sequence, String.valueOf(val));
                    }
                }            
                isValid = AICrossObjectFilterService.evaluate(responseCondition);
            }  
        }
        return isValid;
    }
    
    public static Boolean checkValidityBasedOnAction(String response, AI_Prompt_Response_Validation__c respVal){
        if(respVal.Action__c.equalsIgnoreCase(AIConstants.PROMPT_VALIDATION_ACTION_INCLUDE)){
            if(!response.containsIgnoreCase(respVal.Value__c)){
                return false;
            }
        }else if(respVal.Action__c.equalsIgnoreCase(AIConstants.PROMPT_VALIDATION_ACTION_EXCLUDE)){
            if(response.containsIgnoreCase(respVal.Value__c)){
                return false;
            }
        }else if(respVal.Action__c.equalsIgnoreCase(AIConstants.PROMPT_VALIDATION_ACTION_APEX)){
            Type impl = Type.forName('', respVal.Value__c);
            AIResponseValidationInterface obj = (AIResponseValidationInterface)impl.newInstance();
            return obj.invokeApex(response, respVal);
        }
        return true;
    }
    
}