force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Specify the target object for the prompt.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Prompt_Command__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Command__c</fullName>
    <description>Generated based on other selections.</description>
    <label>Prompt Command</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Only prompts with &apos;Active&apos; status will be available to End User. Ensure to Activate the prompt</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/AI_Prompt_Scheduler__c.object-meta.xml
<CustomObject>
    <label>Prompt Scheduler</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Scheduler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/AI_Scheduler__c.field-meta.xml
<CustomField>
    <fullName>AI_Scheduler__c</fullName>
    <label>AI Mass Processing</label>
    <referenceTo>AI_Scheduler__c</referenceTo>
    <relationshipLabel>Prompt Scheduler</relationshipLabel>
    <relationshipName>Prompt_Scheduler</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <formula>Prompt__r.Object__c</formula>
    <label>Object Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AI_Prompt__c.Type__c</field>
            <operation>notEqual</operation>
            <value>Custom</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>Prompt Scheduler</relationshipLabel>
    <relationshipName>Prompt_Scheduler</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/Record_Limit__c.field-meta.xml
<CustomField>
    <fullName>Record_Limit__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Record Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/Where_Clause__c.field-meta.xml
<CustomField>
    <fullName>Where_Clause__c</fullName>
    <label>Where Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Scheduler__c/AI_Scheduler__c.object-meta.xml
<CustomObject>
    <label>AI Mass Processing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Mass Processing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Scheduler__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AIPromptSchedulerController.cls
/**
* @description       : 
* @author            : Rishabh Goel
* @group             : Plumcloud Labs
* @last modified on  : 01-08-2024
* @last modified by  : Rishabh Goel
**/
public with sharing class AIPromptSchedulerController {
    
    public static final String NAMESPACE = AIPromptController.getNameSpace();

    /**
     * Retrieves data for a specific record identified by the given record ID.
     *
     * @param recordId The unique identifier of the record for which data is requested.
     * @return A Map<String, Object> containing details related to the processing of the specified record.
     *         The keys in the map represent different aspects of the processing, and the corresponding values
     *         are objects containing the relevant data.
     */
    @AuraEnabled
    public static Map<String, Object> getPromptSchedulerData(String recordId){
        try{
            List<Schema.FieldSetMember> fieldSetMembers = SObjectType.AI_Prompt_Scheduler__c.FieldSets.Scheduler_Related_Fields.getFields();
        
            List<Object> fields = new List<Object>();
            List<String> fieldApiNames = new List<String>();
            for(Schema.FieldSetMember fmObj : fieldSetMembers){
                String fieldName = fmObj.getFieldPath();
                String fieldLabel = fmObj.getLabel();
                String fieldType = String.valueOf(fmObj.getType());  
                
                fieldApiNames.add(fieldName);
                
                Boolean isReference = false;
                if(String.isNotBlank(fieldType) && fieldType.equalsIgnoreCase('reference')){
                    isReference = true;
                    
                    String lookupNameField = fieldName;
                    if(lookupNameField.endsWithIgnoreCase('__c')){
                        lookupNameField = lookupNameField.removeEndIgnoreCase('__c')+'__r.Name';
                    }else if(lookupNameField.endsWithIgnoreCase('Id')){
                        lookupNameField = lookupNameField.removeEndIgnoreCase('Id')+'.Name';
                    }
                    fieldApiNames.add(lookupNameField);
                }
                String jsType = 'text';
                if(fieldType.equalsIgnoreCase('DateTime')){
                    jsType = 'date-local';
                }
                
                fields.add(new Map<String, Object>{
                    'label' => fieldLabel, 'fieldName' => fieldName, 'type' => jsType, 'isReference' => isReference
                });
            }
            
            String objName = NAMESPACE+'AI_Prompt_Scheduler__c';
            String parentFieldApi = NAMESPACE+'AI_Scheduler__c';
            String query = 'SELECT Id, '+String.join(fieldApiNames, ', ')+' FROM '+String.escapeSingleQuotes(objName)+' WHERE '+String.escapeSingleQuotes(parentFieldApi)+' =:recordId';
            List<sObject> records = Database.query(query);
            
            return new Map<String, Object>{
                'fields' => fields, 'records' => records
            };
        }catch(Exception e){
            GPTfyException.log(e, 'GPTfy', '', 'AIPromptSchedulerController', 'getPromptSchedulerData', '');
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static Map<String, Object> getPromptSchedulerDetail(String recordId){
        List<AI_Prompt_Scheduler__c> lstOfPromptSchs = [SELECT Id, Object_Name__c, Prompt__c, Prompt__r.Name, Where_Clause__c, Record_Limit__c 
                                                        FROM AI_Prompt_Scheduler__c WHERE Id =:recordId LIMIT 1];
        if(lstOfPromptSchs != null && !lstOfPromptSchs.isEmpty()){
            AI_Prompt_Scheduler__c ps = lstOfPromptSchs.get(0);
            return new Map<String, Object>{
                'id' => ps.Id, 'objectName' => ps.Object_Name__c, 'promptId' => ps.Prompt__c,
                'promptName' => ps.Prompt__r.Name, 'whereClause' => ps.Where_Clause__c, 'recordLimit' => ps.Record_Limit__c 
            };
        }
        return null;
    }
    
    @AuraEnabled
    public static List<Object> getPromptOptions(){
        List<Object> lst = new List<Object>();
        List<AI_Prompt__c> lstOfPrompts = [SELECT Id, Name, Object__c, Prompt_Command__c
                                           FROM AI_Prompt__c 
                                           WHERE Status__c =:AIConstants.PMT_STATUS_ACTIVE];
        if(lstOfPrompts != null && !lstOfPrompts.isEmpty()){
            for(AI_Prompt__c pmt : lstOfPrompts){
                if(String.isNotBlank(pmt.Prompt_Command__c)){
                    lst.add(new Map<String, Object>{
                    	'value' => pmt.Id, 'label' => pmt.Name, 'description' => pmt.Object__c
               		});
                } 
            }
        }
        return lst;
    }
    
    @AuraEnabled
    public static String getPromptObject(String recordId){
        List<AI_Prompt__c> lstOfPrompts = [SELECT Id, Object__c FROM AI_Prompt__c WHERE Id =:recordId LIMIT 1];
        if(lstOfPrompts != null && !lstOfPrompts.isEmpty()){
            return lstOfPrompts.get(0).Object__c;
        }else{
            List<AI_Prompt_Scheduler__c> lstOfPromptSchs = [SELECT Id, Object_Name__c FROM AI_Prompt_Scheduler__c WHERE Id =:recordId LIMIT 1];
            if(lstOfPromptSchs != null && !lstOfPromptSchs.isEmpty()){
                return lstOfPromptSchs.get(0).Object_Name__c;
            }
        }
        return null;
    }

}