force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/Prompt_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Request_Id__c</fullName>
    <label>Prompt Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Scheduler__c/AI_Prompt_Scheduler__c.object-meta.xml
<CustomObject>
    <label>Prompt Scheduler</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Scheduler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/AI_Scheduler__c.field-meta.xml
<CustomField>
    <fullName>AI_Scheduler__c</fullName>
    <label>AI Mass Processing</label>
    <referenceTo>AI_Scheduler__c</referenceTo>
    <relationshipLabel>Prompt Scheduler</relationshipLabel>
    <relationshipName>Prompt_Scheduler</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/AI_Response__c.object-meta.xml
<CustomObject>
    <label>Security Audit</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Audit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Response__c/fields/AI_Processed_Data_PII_Added__c.field-meta.xml
<CustomField>
    <fullName>AI_Processed_Data_PII_Added__c</fullName>
    <inlineHelpText>Response from AI</inlineHelpText>
    <label>AI Processed Data(PII Added)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Prompt that is used</inlineHelpText>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipName>AI_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Scheduled_Run__c/AI_Scheduled_Run__c.object-meta.xml
<CustomObject>
    <label>Scheduled Run</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Run #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Scheduler__c/AI_Scheduler__c.object-meta.xml
<CustomObject>
    <label>AI Mass Processing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Mass Processing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AIPromptResponseProcessingInvokableTest.cls
/**
* @description       : 
* @author            : Adarsh Sharma
* @group             : Plumcloud Labs
* @last modified on  : 08-07-2023
* @last modified by  : Adarsh Sharma
**/
@isTest
public with sharing class AIPromptResponseProcessingInvokableTest {

    @testSetup
    public static void makeData(){
        AI_Scheduler__c sch = TestUtility.getScheduler('Test', 'Daily', '1;1', '0 00 11 ? * * *', Time.newInstance(3, 14, 15, 926), 1, true);
        AI_Prompt__c prompt = TestUtility.getAIPrompt('Test', 'Account', 'Active', false);
        prompt.Prompt_Request_Id__c = 'test';
        insert prompt;
        AI_Prompt_Scheduler__c promptScheduler = TestUtility.getAIPromptScheduler(prompt.Id, sch.Id, true);
        AI_Scheduled_Run__c scheduledRun = TestUtility.getAIScheduledRun(sch.Id, true);
        AI_Response__c response = TestUtility.getAIResponse(scheduledRun.Id, promptScheduler.Id, null, true);
    }
    
    @isTest 
    public static void processRequestResponseIDNOTFOUNDTest(){
        List<AIPromptResponseProcessingInvokable.RequestWrapper> requests = new List<AIPromptResponseProcessingInvokable.RequestWrapper>();
        requests.add(new AIPromptResponseProcessingInvokable.RequestWrapper());
        Test.startTest();
        List<AIPromptResponseProcessingInvokable.ResponseWrapper> responses = AIPromptResponseProcessingInvokable.processRequest(requests);
        System.Assert(responses != null);
        Test.stopTest();
    }
    
    @isTest
    public static void processRequestNoDataToProcessTest(){
        AI_Response__c response = [SELECT Id FROM AI_Response__c limit 1];
        List<AIPromptResponseProcessingInvokable.RequestWrapper> requests = new List<AIPromptResponseProcessingInvokable.RequestWrapper>();
        AIPromptResponseProcessingInvokable.RequestWrapper wrapper = new AIPromptResponseProcessingInvokable.RequestWrapper();
        wrapper.responseId = response.Id;
        requests.add(wrapper);
        Test.startTest();
        List<AIPromptResponseProcessingInvokable.ResponseWrapper> responses = AIPromptResponseProcessingInvokable.processRequest(requests);
        System.Assert(responses != null);
        Test.stopTest();
    }
    
    @isTest
    public static void processRequestMalformedJSONTest(){
        AI_Response__c response = [SELECT Id, AI_Processed_Data_PII_Added__c FROM AI_Response__c limit 1];
        response.AI_Processed_Data_PII_Added__c = 'test';
        update response;
        List<AIPromptResponseProcessingInvokable.RequestWrapper> requests = new List<AIPromptResponseProcessingInvokable.RequestWrapper>();
        AIPromptResponseProcessingInvokable.RequestWrapper wrapper = new AIPromptResponseProcessingInvokable.RequestWrapper();
        wrapper.responseId = response.Id;
        requests.add(wrapper);
        Test.startTest();
        List<AIPromptResponseProcessingInvokable.ResponseWrapper> responses = AIPromptResponseProcessingInvokable.processRequest(requests);
        System.Assert(responses != null);
        Test.stopTest();
    }
    
    @isTest
    public static void processRequestTest(){
        AI_Response__c response = [SELECT Id, AI_Processed_Data_PII_Added__c FROM AI_Response__c limit 1];
        response.AI_Processed_Data_PII_Added__c = '{}';
        update response;
        List<AIPromptResponseProcessingInvokable.RequestWrapper> requests = new List<AIPromptResponseProcessingInvokable.RequestWrapper>();
        AIPromptResponseProcessingInvokable.RequestWrapper wrapper = new AIPromptResponseProcessingInvokable.RequestWrapper();
        wrapper.responseId = response.Id;
        wrapper.key = 'test1';
        requests.add(wrapper);
        Test.startTest();
        List<AIPromptResponseProcessingInvokable.ResponseWrapper> responses = AIPromptResponseProcessingInvokable.processRequest(requests);
        System.Assert(responses != null);
        Test.stopTest();
    }
    
}