force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Scheduler__c/AI_Prompt_Scheduler__c.object-meta.xml
<CustomObject>
    <label>Prompt Scheduler</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Scheduler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Scheduler__c/fields/AI_Scheduler__c.field-meta.xml
<CustomField>
    <fullName>AI_Scheduler__c</fullName>
    <label>AI Mass Processing</label>
    <referenceTo>AI_Scheduler__c</referenceTo>
    <relationshipLabel>Prompt Scheduler</relationshipLabel>
    <relationshipName>Prompt_Scheduler</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/AI_Response__c.object-meta.xml
<CustomObject>
    <label>Security Audit</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Audit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Response__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Prompt that is used</inlineHelpText>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipName>AI_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Scheduled_Run__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Run</label>
    <referenceTo>AI_Scheduled_Run__c</referenceTo>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Scheduled_Run__c/AI_Scheduled_Run__c.object-meta.xml
<CustomObject>
    <label>Scheduled Run</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Run #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Scheduled_Run__c/fields/Scheduler__c.field-meta.xml
<CustomField>
    <fullName>Scheduler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduler</label>
    <referenceTo>AI_Scheduler__c</referenceTo>
    <relationshipLabel>Scheduled Runs</relationshipLabel>
    <relationshipName>Scheduled_Runs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Scheduler__c/AI_Scheduler__c.object-meta.xml
<CustomObject>
    <label>AI Mass Processing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Mass Processing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Scheduler__c/fields/Cron_Expression__c.field-meta.xml
<CustomField>
    <fullName>Cron_Expression__c</fullName>
    <label>Cron Expression</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Scheduler__c/fields/Schedule_Detail__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Detail__c</fullName>
    <label>Schedule Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Scheduler__c/fields/Schedule_time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_time__c</fullName>
    <label>Schedule time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/AI_Scheduler__c/fields/Scheduling_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Scheduling_Frequency__c</fullName>
    <label>Scheduling Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AISchedulerOverrideControllerTest.cls
/**
* @description       : 
* @author            : Rishabh Goel
* @group             : Plumcloud Labs
* @last modified on  : 07-21-2023
* @last modified by  : Rishabh Goel
**/
@isTest
public class AISchedulerOverrideControllerTest {

    @testSetup
    static void makeData(){
        AI_Scheduler__c sch = TestUtility.getScheduler('Test', 'Daily', '1;1', '0 00 11 ? * * *', Time.newInstance(3, 14, 15, 926), 1, true);
        AI_Prompt__c prompt = TestUtility.getAIPrompt('Test', 'Account', 'Active', true);
        AI_Prompt_Scheduler__c promptScheduler = TestUtility.getAIPromptScheduler(prompt.Id, sch.Id, true);
    }
    
    @isTest
    static void getSchedulingInformationTest(){
        AI_Scheduler__c sch = [SELECT Id, Name, Scheduling_Frequency__c, Schedule_Detail__c, Cron_Expression__c, Schedule_time__c, Retry_Count__c FROM AI_Scheduler__c LIMIT 1];
        sch.Cron_Expression__c = '0 00 10 ? * * *';
        update sch;

        Test.startTest();
        Map<String, Object> obj = AISchedulerOverrideController.getSchedulingInformation(sch.Id);
        AISchedulerOverrideController.saveSchedulingInformation(sch.Id, sch.Name, sch.Scheduling_Frequency__c, String.valueOf(sch.Schedule_time__c), sch.Schedule_Detail__c.split(';'), sch.Cron_Expression__c, sch.Retry_Count__c);
        AISchedulerOverrideController.scheduleJob(sch.Id);
        AISchedulerOverrideController.unscheduleJob(sch.Id);
        AISchedulerOverrideController.runNow(sch.Id);
        
        String runId = [SELECT Id FROM AI_Scheduled_Run__c WHERE Scheduler__c != NULL LIMIT 1].Id;
        AI_Response__c resp = new AI_Response__c();
        resp.Scheduled_Run__c = runId;
        insert resp;
        AISchedulerOverrideController.abortJobs(runId);
        Test.stopTest();
        
        System.Assert(obj != null);
    }
    
}