force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/Response_Validation_Condition__c.field-meta.xml
<CustomField>
    <fullName>Response_Validation_Condition__c</fullName>
    <label>Response Validation Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Response_Validation_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Validation_Message__c</fullName>
    <label>Response Validation Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Only prompts with &apos;Active&apos; status will be available to End User. Ensure to Activate the prompt</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/AI_Prompt_Response_Validation__c.object-meta.xml
<CustomObject>
    <label>Prompt Response Validation</label>
    <nameField>
        <displayFormat>RV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Response Validations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>Excludes</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <label>Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>Prompt Response Validations</relationshipLabel>
    <relationshipName>Prompt_Response_Validations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Response_Validation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AIResponseValidationController.cls
/**
* @description       : 
* @author            : Rishabh Goel
* @group             : Plumcloud Labs
* @last modified on  : 07-03-2025
* @last modified by  : Rishabh Goel
**/
public with sharing class AIResponseValidationController {
	
    @AuraEnabled
    public static DataWrapper getResponseValidations(String promptId){
        DataWrapper wrap = new DataWrapper();
        
        List<ValidationWrapper> lstOfValidations = new List<ValidationWrapper>();
        for(AI_Prompt_Response_Validation__c resp : [SELECT Id, Sequence__c, Action__c, Value__c 
                                                     FROM AI_Prompt_Response_Validation__c
                                                     WHERE AI_Prompt__c =:promptId]){
            ValidationWrapper v_wrap = new ValidationWrapper();
            v_wrap.id = resp.Id;
            v_wrap.sequence = resp.Sequence__c != null ? Integer.valueOf(resp.Sequence__c) : null;
            v_wrap.action = resp.Action__c;
            v_wrap.value = resp.Value__c;                                             
            lstOfValidations.add(v_wrap);                                             
        }
        
        AI_Prompt__c pmt = [SELECT Id, Response_Validation_Condition__c, Response_Validation_Message__c, Status__c 
                            FROM AI_Prompt__c 
                            WHERE Id =:promptId LIMIT 1];
        //Jira 7221:  Issues/Feedbacks from 1.12 Testing
        wrap.isPromptActive = (pmt.Status__c == AIConstants.PMT_STATUS_ACTIVE)? true : false;
        wrap.responseValidationCondition = String.isNotBlank(pmt.Response_Validation_Condition__c) ? pmt.Response_Validation_Condition__c : '';
        wrap.responseValidationMessage = String.isNotBlank(pmt.Response_Validation_Message__c) ? pmt.Response_Validation_Message__c : '';
        wrap.responseValidations = lstOfValidations;
        wrap.actionOptions = AIPromptController.getPickListValues(AIConstants.NAMESPACE+'AI_Prompt_Response_Validation__c', AIConstants.NAMESPACE+'Action__c');
        return wrap;
    }
    
    @AuraEnabled
    public static void deleteResponseValidation(String responseValidationId){
        if(String.isNotBlank(responseValidationId)){
            try{
                List<AI_Prompt_Response_Validation__c> lstToDelete = [SELECT Id, Sequence__c, Action__c, Value__c 
                                                                     FROM AI_Prompt_Response_Validation__c
                                                                     WHERE Id =:responseValidationId
                                                                     LIMIT 1];
                FLSCheck.getInstance().deleteDML(lstToDelete);
            }catch(Exception e){
                throw new AuraHandledException(e.getMessage());
            }
        }
    }
    
    @AuraEnabled
    public static void updateResponseValidationCondition(String condition, String message, String recordId){
        condition = String.isNotBlank(condition) ? condition : '';
        if(String.isNotBlank(recordId)){
            AI_Prompt__c pmt = new AI_Prompt__c(
                Id = recordId, 
                Response_Validation_Condition__c = condition,
                Response_Validation_Message__c = message
            );
            FLSCheck.getInstance().updateDML(new List<AI_Prompt__c>{pmt});
        }
    }
    
    @AuraEnabled
    public static void upsertResponseValidation(Map<String, String> data){
        try{
            String promptId = data.get('promptId');
            String responseValidationId = data.get('responseValidationId');
            String validationAction = data.get('validationAction');
            String validationValue = data.get('validationValue');
            String sequence = data.get('sequence');
    
            if(String.isNotBlank(promptId)){
                AI_Prompt_Response_Validation__c resp = new AI_Prompt_Response_Validation__c();
                resp.Action__c = validationAction;
                resp.Sequence__c = String.isNotBlank(sequence) ? Integer.valueOf(sequence) : 1;
                resp.Value__c = validationValue;
                if(String.isNotBlank(responseValidationId)){
                    resp.Id = responseValidationId;
                    FLSCheck.getInstance().updateDML(new List<AI_Prompt_Response_Validation__c>{resp});
                }else{
                    resp.AI_Prompt__c = promptId;
                    FLSCheck.getInstance().insertDML(new List<AI_Prompt_Response_Validation__c>{resp});
                }
            }
        }catch(Exception e){
        	throw new AuraHandledException(e.getMessage());
        }
    }
    
    public class DataWrapper{
        @AuraEnabled public String responseValidationCondition{get;set;}
        @AuraEnabled public String responseValidationMessage{get;set;}
        @AuraEnabled public List<ValidationWrapper> responseValidations{get;set;}
        @AuraEnabled public List<AIDataExtractionController.PicklistWrapper> actionOptions{get;set;}
        @AuraEnabled public Boolean isPromptActive{get;set;}
    }
    
    public class ValidationWrapper{
        @AuraEnabled public String id{get;set;}
        @AuraEnabled public Integer sequence{get;set;}
        @AuraEnabled public String action{get;set;}
        @AuraEnabled public String value{get;set;}
    }
    
}