force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/AI_Data_Extraction_Detail__c.object-meta.xml
<CustomObject>
    <label>Data Context Detail</label>
    <nameField>
        <label>Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <label>AI Data Extraction Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/AI_Data_Extraction_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Context Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Target Object</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Connection__c.field-meta.xml
<CustomField>
    <fullName>AI_Connection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AI Model</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the mapping created for the prompt</inlineHelpText>
    <label>Data Context Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Only prompts with &apos;Active&apos; status will be available to End User. Ensure to Activate the prompt</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt_Action__c/AI_Prompt_Action__c.object-meta.xml
<CustomObject>
    <label>Prompt Action</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Action #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Prompt_Action</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt_Action__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <label>Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>Prompt Actions</relationshipLabel>
    <relationshipName>Prompt_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Action_Detail__c/AI_Prompt_Action_Detail__c.object-meta.xml
<CustomObject>
    <label>Prompt Action Detail</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>Detail #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Action Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Action_Detail__c/fields/AI_Prompt_Action__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt_Action__c</fullName>
    <label>Prompt Action</label>
    <referenceTo>AI_Prompt_Action__c</referenceTo>
    <relationshipLabel>Prompt Action Details</relationshipLabel>
    <relationshipName>Prompt_Action_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Action_Detail__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Component__c/AI_Prompt_Component__c.object-meta.xml
<CustomObject>
    <label>Prompt Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Component__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>AI Prompt Components</relationshipLabel>
    <relationshipName>AI_Prompt_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Component__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chain of Thought</fullName>
            </value>
            <value>
                <fullName>Next Best Action</fullName>
            </value>
            <value>
                <fullName>Draft Email</fullName>
            </value>
            <value>
                <fullName>Sentiment</fullName>
            </value>
            <value>
                <fullName>Sentiment Score</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
                <default>true</default>
                <label>Summary</label>
            </value>
            <value>
                <fullName>Root Cause Analysis</fullName>
            </value>
            <value>
                <fullName>Corrective Action</fullName>
            </value>
            <value>
                <fullName>Intent Analysis</fullName>
            </value>
            <value>
                <fullName>Identify Language</fullName>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
            <value>
                <fullName>Identify Product</fullName>
            </value>
            <value>
                <fullName>Identify Request Type</fullName>
            </value>
            <value>
                <fullName>Root Cause Reason</fullName>
            </value>
            <value>
                <fullName>Resolution</fullName>
            </value>
            <value>
                <fullName>Categorize</fullName>
            </value>
            <value>
                <fullName>True or False</fullName>
            </value>
            <value>
                <fullName>Title</fullName>
            </value>
            <value>
                <fullName>Article type</fullName>
            </value>
            <value>
                <fullName>Problem statement</fullName>
            </value>
            <value>
                <fullName>Knowledge URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Response__c/AI_Response__c.object-meta.xml
<CustomObject>
    <label>Security Audit</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Audit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Response__c/fields/AI_Processed_Data_PII_Added__c.field-meta.xml
<CustomField>
    <fullName>AI_Processed_Data_PII_Added__c</fullName>
    <inlineHelpText>Response from AI</inlineHelpText>
    <label>AI Processed Data(PII Added)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Prompt that is used</inlineHelpText>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipName>AI_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Data Extracted</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Errored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Security_Filters__c/AI_Security_Filters__c.object-meta.xml
<CustomObject>
    <label>Security Layer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Security Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Security_Filters__c/fields/Search_Pattern__c.field-meta.xml
<CustomField>
    <fullName>Search_Pattern__c</fullName>
    <inlineHelpText>Reguler Expression</inlineHelpText>
    <label>Search Pattern</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Security_Filters__c/recordTypes/Regex.recordType-meta.xml
<RecordType>
    <fullName>Regex</fullName>
    <active>true</active>
    <label>Regex</label>
</RecordType>

force-app/main/default/classes/GPTfyConsoleControllerTest.cls
/**
* @description       : 
* @author            : Rishabh Goel
* @group             : Plumcloud Labs
* @last modified on  : 03-28-2023
* @last modified by  : Rishabh Goel
**/
@isTest
public with sharing class GPTfyConsoleControllerTest {
	
    @testSetup
    static void makeData(){
        AI_Connection__c conn = TestUtility.getConnection('GPTfy', true);
        TestUtility.insertDataExtraction();
        AI_Data_Extraction_Mapping__c master = [SELECT Id FROM AI_Data_Extraction_Mapping__c LIMIT 1];
        String pmtId = AIPromptController.saveAIPrompt(new Map<String, Object>{
            'targetObject' => 'Account', 'aiConnection' => conn.Id, 'promptName' => 'Test Prompt', 'extractionMappingId' => master.Id,
            'selectedType' => 'JSON', 'promptCommand' => 'Give a sample response.'
        });
        AI_Prompt_Component__c cmp1 = TestUtility.getPromptComponent(pmtId, master.Id, 'Account', false);
        cmp1.Key__c = 'Sentiment';
        insert cmp1;
        
        AI_Data_Extraction_Detail__c cDetail = [SELECT Id FROM AI_Data_Extraction_Detail__c WHERE Object_Name__c = 'Contact' LIMIT 1];
        AI_Prompt_Component__c cmp2 = TestUtility.getPromptComponent(pmtId, cDetail.Id, 'Contact', true);
        
        AI_Data_Extraction_Detail__c gcDetail = [SELECT Id FROM AI_Data_Extraction_Detail__c WHERE Object_Name__c = 'Case' LIMIT 1];
        AI_Prompt_Component__c cmp3 = TestUtility.getPromptComponent(pmtId, gcDetail.Id, 'Case', true);
        AIJsonGeneration.generatePromptCommand(pmtId);
        AI_Prompt_Action__c action = TestUtility.getAIPromptAction(pmtId,AIConstants.ACTION_TYPE_UPDATE_FIELD, false);
        action.Field_API_Name__c = 'Name';
        action.Object_Name__c = 'Account';
        insert action;
        AI_Prompt_Action__c actionCreateRecord = TestUtility.getAIPromptAction(pmtId,AIConstants.ACTION_TYPE_CREATE_RECORD, false);
        actionCreateRecord.Object_Name__c = 'Account';
        insert actionCreateRecord;
        AI_Prompt_Action_Detail__c actionDetails = TestUtility.getAIPromptActionDetail(actionCreateRecord.Id,'Name',AIConstants.ACTION_DETAIL_TYPE_HARDCODED, false);
        actionDetails.Value__c = 'TestValue';
        insert actionDetails;
    }
    
    @isTest
    static void getPromptOptionsTest(){
        Account acc = new Account(name = 'test account');
        insert acc;
        AI_Prompt__c aiPrompt = [SELECT Id FROM AI_Prompt__c limit 1];
        AI_Prompt_Action__c action = new AI_Prompt_Action__c(Object_Name__c= 'Account',Description__c='test',
                                                            Action__c=AIConstants.ACTION_TYPE_OPEN_FORM,AI_Prompt__c=aiPrompt.Id);
        insert action;
        Test.startTest();
        Boolean hasPortalUser = GPTfyConsoleController.isPortalUser();
        Boolean isAdminUser = GPTfyConsoleController.isAdminUser();
        GPTfyConsoleController.getPromptActionOptionsOpenForm(aiPrompt.Id);
        System.Assert(hasPortalUser != true);
        Map<String, Object> data = GPTfyConsoleController.getPromptOptions(acc.Id, NULL);
        GPTfyConsoleController.getLatestRecordOfSecurityAudit(aiPrompt.Id);
        Test.stopTest();
        System.Assert(data != null);
    }
    
    @isTest
    static void checkValidationVisibilityCondition(){
        AI_Security_Filters__c secfilter = new AI_Security_Filters__c(name = 'test security filters');
        secfilter.RecordTypeId = Schema.SObjectType.AI_Security_Filters__c.getRecordTypeInfosByDeveloperName().get('Regex').getRecordTypeId();
        secfilter.Search_Pattern__c = 'abc';
        insert secfilter;
        Test.startTest();
        Boolean isValid = GPTfyConsoleController.isValidVisibilityCondition(null,secfilter.Id, 'Name = \'test security filters\' LIMIT 1',new List<String> {'Regex'});
        System.Assert(isValid == true);
        Test.stopTest();
    }
    
    @isTest
    static void checkForContentVersionsTest(){
        Account acc = new Account(name = 'test account');
        insert acc;
         
        Contentversion cv = TestUtility.getContentversion('Test', 'Test', 'Test', false);
        insert cv;

        cv = [SELECT Id, ContentDocumentId FROM ContentVersion where Id = :cv.Id]; 
        
        ContentDocumentLink cdl = TestUtility.getContentDocumentLink(acc.Id, cv.ContentDocumentId, false);
        insert cdl;
        
        AI_Prompt__c aiPrompt = [SELECT Id FROM AI_Prompt__c limit 1];
        Test.startTest();
        List<GPTfyConsoleController.RecordWrapper> data = GPTfyConsoleController.checkForContentVersions(acc.Id, aiPrompt.Id);
        Test.stopTest();
        System.Assert(data != null);
    }
    
    @isTest
    static void saveFeedbackTest(){
        Account acc = new Account(name = 'test account');
        insert acc;
        List<AI_Prompt_Action__c> pActions = [Select Id,Field_API_Name__c from AI_Prompt_Action__c];
        AI_Response__c resp = new AI_Response__c();
        resp.AI_Prompt__c = [SELECT Id FROM AI_Prompt__c limit 1].Id;
        resp.AI_Processed_Data_PII_Added__c = 'test';
        resp.Status__c = AIConstants.RESP_STATUS_PROCESSED;
        resp.Record_Id__c = acc.Id;
        insert resp;
        
        List<AI_Response__c> respList = GPTfyConsoleController.getAllResponses(acc.Id);
        List<AI_Response__c> respSecurityAuditList = GPTfyConsoleController.getSecurityAudit(resp.Id);
        
        Test.startTest();
        GPTfyConsoleController.saveFeedback(respSecurityAuditList[0].Id, 'Dislike', '', '');
        for(AI_Prompt_Action__c a : pActions){
             GPTfyConsoleController.getDefaultFieldsString(a.Id,resp.Id);
        }
        Test.stopTest();
        System.assert(respSecurityAuditList != null);
    }
    
}