force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/AI_Data_Extraction_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Context Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Connection__c.field-meta.xml
<CustomField>
    <fullName>AI_Connection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AI Model</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the mapping created for the prompt</inlineHelpText>
    <label>Data Context Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/AI_Response__c.object-meta.xml
<CustomObject>
    <label>Security Audit</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Audit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Response__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Prompt that is used</inlineHelpText>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipName>AI_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPTfy_Settings__c/GPTfy_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>GPTfy Settings</label>
</CustomObject>

force-app/main/default/objects/GPTfy_Settings__c/fields/Blank_Replacement_Value__c.field-meta.xml
<CustomField>
    <fullName>Blank_Replacement_Value__c</fullName>
    <label>Blank Replacement Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPTfy_Settings__c/fields/Typewriter_Effect__c.field-meta.xml
<CustomField>
    <fullName>Typewriter_Effect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Typewriter Effect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AIGlobalUtilityTest.cls
@isTest
public class AIGlobalUtilityTest {
	
    @testSetup
    static void makeData(){
        Account acc = new Account(Name = 'Test Account22');
        insert acc;
        
        AI_Connection__c conn = TestUtility.getConnection('GPTfy', true);
        TestUtility.insertDataExtraction();
        AI_Data_Extraction_Mapping__c master = [SELECT Id FROM AI_Data_Extraction_Mapping__c LIMIT 1];
        String pmtId = AIPromptController.saveAIPrompt(new Map<String, Object>{
            'targetObject' => 'Account', 'aiConnection' => conn.Id, 'promptName' => 'Test Prompt', 'extractionMappingId' => master.Id,
            'selectedType' => 'JSON', 'promptCommand' => 'Give a sample response.', 'groundingContent' => 'Only answer what has been asked for.', 
            'groundingEthical' => 'Do not hallucinate.'
        });
    }
    
    @isTest
    static void getExtractedDataTest(){
        Account a = [SELECT Id FROM Account LIMIT 1];
        AI_Prompt__c pmt = [SELECT Id FROM AI_Prompt__c LIMIT 1];
        
        Test.startTest();
        AI_Response__c resp = AIGlobalUtility.getExtractedData(a.Id, pmt.Id);
        Test.stopTest();
        System.assert(resp != NULL);
    }
    
    @isTest
    static void aiUtilityTest(){
        Test.startTest();
        AIUtility.updateGPTfySettings(AIConstants.NAMESPACE+'Blank_Replacement_Value__c', 'Test2');
        AIUtility.updateCustomSettings(AIConstants.NAMESPACE+'Typewriter_Effect__c', true);
        Test.stopTest();
        GPTfy_Settings__c settings = [Select id,Blank_Replacement_Value__c from GPTfy_Settings__c where Blank_Replacement_Value__c='Test2'];
        System.assert(settings != NULL);
    }
    
}