force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/AI_Data_Extraction_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Context Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <formula>(&quot;AI_Data_Extraction_Mapping__c&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Target Object</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AIDataExtractionCloningControllerTest.cls
@isTest
private class AIDataExtractionCloningControllerTest {
    
    @testSetup
    static void makeData(){
        AI_Connection__c conn = TestUtility.getConnection('GPTfy', true);
        TestUtility.insertDataExtraction();
    }
    
    @isTest 
    private static void testcloneRecord(){     
        AI_Data_Extraction_Mapping__c master = [SELECT Id, Name, API_Name__c, Description__c, Object_Name__c, External_Id__c FROM AI_Data_Extraction_Mapping__c LIMIT 1];
        String cloneRecordId = AIDataExtractionCloningController.cloneRecord(master.Id);
        system.assertEquals(String.isNotBlank(cloneRecordId), true);
    }
}