force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Connection__c/fields/Additional_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Additional_Parameters__c</fullName>
    <label>Additional Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Connection__c/fields/Async_Request__c.field-meta.xml
<CustomField>
    <fullName>Async_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Async Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Connection__c/fields/Connector_Class__c.field-meta.xml
<CustomField>
    <fullName>Connector_Class__c</fullName>
    <description>Optional customer-created Apex interface class. If a value is provided here, GPTfy will use that to retrieve the token to call the customer-hosted AI service.</description>
    <label>Connector Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Connection__c/fields/Processing_Class__c.field-meta.xml
<CustomField>
    <fullName>Processing_Class__c</fullName>
    <label>Processing Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/AI_Voice_Configuration__c.object-meta.xml
<CustomObject>
    <label>Voice Configuration</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Configuration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/AI_Model__c.field-meta.xml
<CustomField>
    <fullName>AI_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Model (Processing)</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>Voice Configurations</relationshipLabel>
    <relationshipName>Voice_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/AI_Model_File_Upload__c.field-meta.xml
<CustomField>
    <fullName>AI_Model_File_Upload__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Model (File Upload)</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>Voice Configurations (AI Model (File Upload))</relationshipLabel>
    <relationshipName>Voice_Configurations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/AI_Model_Polling__c.field-meta.xml
<CustomField>
    <fullName>AI_Model_Polling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Model (Polling)</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>Voice Configurations (AI Model (Polling))</relationshipLabel>
    <relationshipName>Voice_Configurations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/Maximum_Polling_Counter__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Polling_Counter__c</fullName>
    <label>Maximum Polling Counter</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/Polling_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Polling_Timeframe__c</fullName>
    <label>Polling Timeframe (in mins)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AudioRecorderController.cls
global with sharing class AudioRecorderController {
    public static final String NAMESPACE = AIPromptController.getNameSpace();
	
    /*
    This method will be called on click submit audio to google chrip for transcript
    params : isIOS is true if the request is for IOS, false for Android
    params : cdId is the content document Id
    params : recordId is the record Id
    */
    @AuraEnabled
    global static void createContentDocumentLink(String cdId, String recordId, Boolean isIOS){
        List<ContentVersion> lstOfVersions = [SELECT Id, VersionData, ContentDocumentId, Title 
                                              FROM ContentVersion
                                              WHERE Id =:cdId];
        if(lstOfVersions != null && lstOfVersions.size() > 0){
            // v2/7290 : GPTfy Voice Enhancements : Added  AI_Model__r.Connector_Class__c,  AI_Model__r.Processing_Class__c
            List<AI_Voice_Configuration__c> lstOfConfigs = [SELECT Id, Async_Request__c, Polling_Timeframe__c, Maximum_Polling_Counter__c,
                                                            AI_Model__c, AI_Model__r.Connector_Class__c, AI_Model__r.Named_Credential__c, AI_Model__r.EndPoint_URL__c, 
                                                            AI_Model__r.Model__c, AI_Model__r.Additional_Parameters__c, AI_Model__r.Processing_Class__c,
                                                            AI_Model_File_Upload__c, AI_Model_File_Upload__r.Named_Credential__c, AI_Model_File_Upload__r.EndPoint_URL__c, 
                                                            AI_Model_File_Upload__r.Model__c, AI_Model_File_Upload__r.Additional_Parameters__c,
                                                            AI_Model_Polling__c, AI_Model_Polling__r.Named_Credential__c, AI_Model_Polling__r.EndPoint_URL__c, 
                                                            AI_Model_Polling__r.Model__c, AI_Model_Polling__r.Additional_Parameters__c
                                                            FROM AI_Voice_Configuration__c 
                                                            WHERE AI_Model__c != NULL
                                                            LIMIT 1];
            if(lstOfConfigs != null && !lstOfConfigs.isEmpty()){
                AIAudioProcessingService.ProcessAudioWrapper wrap = new AIAudioProcessingService.ProcessAudioWrapper();
                wrap.audioConfig = lstOfConfigs.get(0);
                wrap.cv = lstOfVersions.get(0);
                wrap.recordId = recordId;
                wrap.isIOS = isIOS;
                AIAudioProcessingService.processFile(wrap);
            }
        }
    }
    
    /*
    This method will be called on initialize Audio Controller for check User Authorized with Permission Set Admin, User, Portal.
    */
    @AuraEnabled
    public static Boolean isUserAuthorized(){
    	String l_namespace = NAMESPACE;
        if(String.isNotBlank(l_namespace) && l_namespace.endsWithIgnoreCase('__')){
            l_namespace = l_namespace.removeEndIgnoreCase('__');
        }
        
        List<PermissionSetAssignment> permSetAssignments = [SELECT Id FROM PermissionSetAssignment 
                                                            WHERE AssigneeId =:UserInfo.getUserId()
                                                            AND (PermissionSet.Name =:AIConstants.GPTFY_ADMIN_PERM_SET
                                                            OR PermissionSet.Name =:AIConstants.GPTFY_VOICE_PERM_SET)
                                                            AND PermissionSet.NamespacePrefix =:l_namespace];
        if(permSetAssignments == null || permSetAssignments.isEmpty()){
            return false;
        }
        return true;
    }
}