force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Connection__c/fields/Max_Total_Tokens__c.field-meta.xml
<CustomField>
    <fullName>Max_Total_Tokens__c</fullName>
    <label>Max Total Tokens</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Connection__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <inlineHelpText>Used to evoke sensory experience like high for serious answer and low for creativity</inlineHelpText>
    <label>Temperature</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Connection__c.field-meta.xml
<CustomField>
    <fullName>AI_Connection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AI Model</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Grounding_Content__c.field-meta.xml
<CustomField>
    <fullName>Grounding_Content__c</fullName>
    <inlineHelpText>This category focuses on the style, clarity, and organization of responses. It includes guidelines on language usage, adherence to local conventions, and the structure of the response to ensure it is clear, direct, and easily understandable. These guidelines help in maintaining a professional and coherent communication style that enhances the effectiveness and accessibility of the information provided.</inlineHelpText>
    <label>Grounding - Content</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address all parts of a multi-part question.</fullName>
            </value>
            <value>
                <fullName>Aim for clarity over complexity.</fullName>
            </value>
            <value>
                <fullName>Avoid using absolutes, such as &quot;always&quot; or &quot;never&quot;.</fullName>
            </value>
            <value>
                <fullName>Avoid using passive voice.</fullName>
            </value>
            <value>
                <fullName>Avoid using slang or colloquial terms unless specifically asked.</fullName>
            </value>
            <value>
                <fullName>Only answer what has been asked for.</fullName>
            </value>
            <value>
                <fullName>Refrain from using first-person pronouns.</fullName>
            </value>
            <value>
                <fullName>Ensure all records are shown in the tables.</fullName>
            </value>
            <value>
                <fullName>Include border=&quot;1&quot; in all HTML table tags</fullName>
            </value>
            <value>
                <fullName>Add captions to each HTML table.</fullName>
            </value>
            <value>
                <fullName>Prioritize quality over speed in responses.</fullName>
            </value>
            <value>
                <fullName>Convert all internal CSS to inline CSS for the response.</fullName>
            </value>
            <value>
                <fullName>Use the following inline CSS for table header &apos;th&apos; style=&quot;background-color: #e1ebf7 color: #16325  padding: 0.5rem text-align: left&quot;</fullName>
            </value>
            <value>
                <fullName>Use the following inline CSS for caption = &quot;font-size: 1.0rem font-weight: bold padding: 0.5rem color: #5C5C5C text-align: left&quot;</fullName>
            </value>
            <value>
                <fullName>Dont add any &apos;\n&apos; characters in your HTML. Replace each &apos;\n&apos; with the HTML line break tag &lt;br&gt;. Ensure the rest of the text is properly wrapped in HTML tags, like &lt;p&gt; for paragraphs, to maintain the formatting.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Grounding_Ethical__c.field-meta.xml
<CustomField>
    <fullName>Grounding_Ethical__c</fullName>
    <inlineHelpText>This category emphasizes ethical and safe communication. It focuses on producing respectful and responsible content, ensuring truthfulness, and avoiding any offensive or misleading information. It also prioritizes protecting individuals from physical, psychological, or informational harm. These guidelines advocate for dignified, conscientious communication, blending ethical principles with a commitment to safety and security in all interactions.</inlineHelpText>
    <label>Grounding - Ethical</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Avoid using emotive language.</fullName>
            </value>
            <value>
                <fullName>Do not exaggerate.</fullName>
            </value>
            <value>
                <fullName>Do not generate content that can be deemed offensive or inappropriate.</fullName>
            </value>
            <value>
                <fullName>Do not hallucinate.</fullName>
            </value>
            <value>
                <fullName>Do not use scare tactics.</fullName>
            </value>
            <value>
                <fullName>Prioritize safety and ethical considerations in your answers.</fullName>
            </value>
            <value>
                <fullName>Your response must be based on the information provided in the prompt.</fullName>
            </value>
            <value>
                <fullName>Use data from the provided JSON, linked by 18-digit IDs</fullName>
            </value>
            <value>
                <fullName>Task summary must always include names and titles of people involved</fullName>
            </value>
            <value>
                <fullName>Write summaries in third person and condense key points.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/How_it_works__c.field-meta.xml
<CustomField>
    <fullName>How_it_works__c</fullName>
    <label>How it Works?</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Specify the target object for the prompt.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Profiles__c.field-meta.xml
<CustomField>
    <fullName>Profiles__c</fullName>
    <label>Profiles</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Prompt_Command__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Command__c</fullName>
    <description>Generated based on other selections.</description>
    <label>Prompt Command</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Prompt_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Request_Id__c</fullName>
    <label>Prompt Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Only prompts with &apos;Active&apos; status will be available to End User. Ensure to Activate the prompt</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/AI_Response__c.object-meta.xml
<CustomObject>
    <label>Security Audit</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Audit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Response__c/fields/AI_Processed_Data_PII_Added__c.field-meta.xml
<CustomField>
    <fullName>AI_Processed_Data_PII_Added__c</fullName>
    <inlineHelpText>Response from AI</inlineHelpText>
    <label>AI Processed Data(PII Added)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Prompt that is used</inlineHelpText>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipName>AI_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/How_it_works__c.field-meta.xml
<CustomField>
    <fullName>How_it_works__c</fullName>
    <label>How it works</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Prompt_Command__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Command__c</fullName>
    <inlineHelpText>Prompt command sent to AI.</inlineHelpText>
    <label>Prompt Command</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Data Extracted</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Errored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/AI_Voice_Configuration__c.object-meta.xml
<CustomObject>
    <label>Voice Configuration</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Configuration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AIRealTimeVoiceController.cls
public with sharing class AIRealTimeVoiceController {
	/*
    @AuraEnabled
    public static InitWrapper getInitDetails(){
        InitWrapper i_wrap = new InitWrapper();
        List<AI_Voice_Configuration__c> configs = [SELECT Id, AI_Model_Agentic__c
                                                   FROM AI_Voice_Configuration__c
                                                   LIMIT 1];
        if(configs != null && !configs.isEmpty() && configs.get(0).AI_Model_Agentic__c != null){
            //i_wrap.endpoint = configs.get(0).AI_Model_Agentic__c;
            
            Set<String> promptNames = new Set<String>();
            Set<String> objectTypes = new Set<String>();
            List<PromptWrapper> lstOfPrompts = new List<PromptWrapper>();
            String profileName = [SELECT Id, Name 
                                  FROM Profile 
                                  WHERE Id =:UserInfo.getProfileId() 
                                  LIMIT 1].Name;
            
            for(AI_Prompt__c pmt : [SELECT Id, Name, Object__c, Profiles__c, Description__c, How_It_Works__c, 
                                    Grounding_Ethical__c, Grounding_Content__c, Prompt_Command__c
                                    FROM AI_Prompt__c 
                                    WHERE Status__c =:AIConstants.PMT_STATUS_ACTIVE
                                    AND Available_for_Agentic__c = True]){
                if((String.isBlank(pmt.Profiles__c) || pmt.Profiles__c.containsIgnoreCase(profileName))){
                    promptNames.add(pmt.Name);
                	objectTypes.add(pmt.Object__c);
                    
                    PromptWrapper p_wrap = new PromptWrapper();
                    p_wrap.promptId = pmt.Id;
                    p_wrap.promptName = pmt.Name;
                    p_wrap.objectType = pmt.Object__c;
                    p_wrap.description = pmt.Description__c;
                    p_wrap.howItWorks = pmt.How_It_Works__c;
                    p_wrap.groundingEthical = pmt.Grounding_Ethical__c;
                    p_wrap.groundingContent = pmt.Grounding_Content__c;
                    p_wrap.promptCommand = pmt.Prompt_Command__c;
                    lstOfPrompts.add(p_wrap);
                }
            }
            
            if(!promptNames.isEmpty()){
                i_wrap.promptNames = new List<String>(promptNames);
                i_wrap.objectTypes = new List<String>(objectTypes);
                i_wrap.prompts = lstOfPrompts;
            }
        }
        return i_wrap;
    }
    
    public class InitWrapper{
        @AuraEnabled public String endpoint{get;set;}
        @AuraEnabled public List<String> promptNames{get;set;}
        @AuraEnabled public List<String> objectTypes{get;set;}
        @AuraEnabled public List<PromptWrapper> prompts{get;set;}
    }
    
    public class PromptWrapper{
        @AuraEnabled public String promptId{get;set;}
        @AuraEnabled public String promptName{get;set;}
        @AuraEnabled public String objectType{get;set;}
        @AuraEnabled public String description{get;set;}
        @AuraEnabled public String howItWorks{get;set;}
        @AuraEnabled public String groundingEthical{get;set;}
        @AuraEnabled public String groundingContent{get;set;}
        @AuraEnabled public String promptCommand{get;set;}
    }
    
    
    @AuraEnabled
    public static List<Object> findRecordsUsingSearchKey(String promptName, String searchKey){
        List<Object> data = new List<Object>();
        promptName = '%'+promptName+'%';
        searchKey = '%'+searchKey+'%';
        List<AI_Prompt__c> lstOfPrompts = [SELECT Id, Name, Object__c, Prompt_Request_Id__c, 
                                           Record_Finder_Filter__c, Record_Finder_Fields__c
                                           FROM AI_Prompt__c
                                           WHERE Name LIKE :promptName 
                                           AND Status__c =:AIConstants.PMT_STATUS_ACTIVE
                                           LIMIT 1];
        
        if(lstOfPrompts != null && !lstOfPrompts.isEmpty()){
            AI_Prompt__c pmt = lstOfPrompts.get(0);
            String objName = pmt.Object__c;
            if(String.isNotBlank(pmt.Record_Finder_Filter__c)){
                String query = ' SELECT Id ';
                if(String.isNotBlank(pmt.Record_Finder_Fields__c)){
                    query += ', '+String.escapeSingleQuotes(pmt.Record_Finder_Fields__c);
                }
                query += ' FROM '+String.escapeSingleQuotes(objName);
                query += ' WHERE '+pmt.Record_Finder_Filter__c;
                
                Map<String, Object> bindMap = new Map<String, Object>{'searchKey' => searchKey};
				List<sObject> records =  Database.queryWithBinds(query, bindMap, AccessLevel.USER_MODE);
                
                if(records != null && !records.isEmpty()){
                    Map<String, Schema.SObjectField> initialFieldMap = AIDataExtractionService.schemaMap.get(objName).getDescribe().fields.getMap();
                    Map<String, Schema.SObjectField> fieldMap = new Map<String, Schema.SObjectField>();
                    for(String fName : initialFieldMap.keySet()){
                        fieldMap.put(fName.toLowerCase(), initialFieldMap.get(fName));
                    }
                    
                    for(sObject so : records){
                       	Map<String, Object> sObjMap = new Map<String, Object>();
                        sObjMap.put('Id', so.get('Id'));
                        if(String.isNotBlank(pmt.Record_Finder_Fields__c)){
                            List<String> finderFields = pmt.Record_Finder_Fields__c.split(',');
                            for(String fName : finderFields){
                                String fieldName = fName.toLowerCase().trim();
                                if(fieldMap != null && fieldMap.containsKey(fieldName)){
                                   	DescribeFieldResult fDesc = fieldMap.get(fieldName).getDescribe();
                                    String fieldLabel = fDesc.getLabel();
                                    sObjMap.put(fieldLabel, so.get(fName.trim()));
                                }
                            }
                        }
                        data.add(sObjMap);
                    }
                }
            }
        }
        
        return data;
    } 
    
    @AuraEnabled
    public static String getExtractedData(String promptName, String recordId){
        String promptSearchKey = '%'+promptName+'%';
        List<AI_Prompt__c> lstOfPrompts = [SELECT Id, Name, Object__c, Prompt_Request_Id__c, 
                                           Record_Finder_Filter__c, Record_Finder_Fields__c
                                           FROM AI_Prompt__c
                                           WHERE Name LIKE :promptSearchKey 
                                           AND Status__c =:AIConstants.PMT_STATUS_ACTIVE
                                           LIMIT 1];
        
        if(lstOfPrompts != null && !lstOfPrompts.isEmpty()){
            AI_Prompt__c pmt = lstOfPrompts.get(0);
            AI_Response__c resp = AIGlobalUtility.getExtractedData(recordId, pmt.Id);
            return resp.AI_Processed_Data_PII_Added__c;
        }
        return null;
    }
    
    @AuraEnabled
    public static String sendMessageToAzureChatBot(List<Map<String, String>> messages) {
        List<AI_Voice_Configuration__c> configs = [SELECT Id, AI_Model_Agentic__c
                                                   FROM AI_Voice_Configuration__c
                                                   LIMIT 1];
        if(configs != null && !configs.isEmpty() && configs.get(0).AI_Model_Agentic__c != null){
            List<AI_Connection__c> agenticModel = [SELECT Id,EndPoint_URL__c, Named_Credential__c,Temperature__c,Max_Total_Tokens__c 
                                                   FROM AI_Connection__c 
                                                   WHERE Id=:configs.get(0).AI_Model_Agentic__c 
                                                   LIMIT 1];
            
            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:'+agenticModel[0].Named_Credential__c+agenticModel[0].EndPoint_URL__c);
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json');
           // req.setHeader('api-key', '9FzRxq2nMHNzlduqmGEozrwJ5o9Ittb57A0SGOPTzwVvS7Otjb6NJQQJ99ALACHYHv6XJ3w3AAAAACOGIjot');
            
            Map<String, Object> body = new Map<String, Object>{
                'messages' => messages,
                //'max_tokens' => 150,
                'temperature' => agenticModel[0].Temperature__c,
                    'max_completion_tokens' => agenticModel[0].Max_Total_Tokens__c
            };
            
            req.setBody(JSON.serialize(body));
            
            // Return streaming response
            Http http = new Http();
            HttpResponse res = http.send(req);
            
            if (res.getStatusCode() == 200) {
                // Handle streaming response
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                List<Object> choices = (List<Object>) responseMap.get('choices');
                Map<String, Object> choiceObj = (Map<String, Object>) choices[0];
                Map<String, Object> message = (Map<String, Object>) choiceObj.get('message');
                return (String) message.get('content');
            } else {
                return 'Error from OpenAI: ' + res.getBody();
            }
        }else {
                return 'AI Model Agentic not define in Voice Configuration.';
        }
        
        
    }*/
    
    /*
    @AuraEnabled
    public static List<SObject> getObjectByName(String objectName, String name) {
        System.debug('Object Name: ' + objectName +', Name: ' + name);
        name = '%'+name+'%';
        // Construct the dynamic query string
        String query = 'SELECT Id, Name FROM ' + objectName + ' WHERE Name LIKE :name LIMIT 1';
    
        try {
            // Execute the dynamic query
            return Database.query(query);
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            throw new AuraHandledException('Failed to fetch records. Please check your inputs.');
        }
    }

    
    @AuraEnabled
    public static List<AI_Prompt__c> getPromptByName(String promptName) {
        System.debug('prompt name: '+promptName);
        String nm = '%' + promptName + '%';
        return [
            SELECT Id, Name, Prompt_Request_Id__c
            FROM AI_Prompt__c
            WHERE Name LIKE :nm LIMIT 1
        ];
    }
    */
    
}