force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/AI_Data_Extraction_Detail__c.object-meta.xml
<CustomObject>
    <label>Data Context Detail</label>
    <nameField>
        <label>Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <label>AI Data Extraction Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/AI_Data_Extraction_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Context Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Target Object</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Connection__c.field-meta.xml
<CustomField>
    <fullName>AI_Connection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AI Model</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the mapping created for the prompt</inlineHelpText>
    <label>Data Context Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Pre_Packaged__c.field-meta.xml
<CustomField>
    <fullName>Pre_Packaged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Packaged?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Only prompts with &apos;Active&apos; status will be available to End User. Ensure to Activate the prompt</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Setup_Settings__c/Setup_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Setup Settings</label>
</CustomObject>

force-app/main/default/objects/Setup_Settings__c/fields/Candidates_1__c.field-meta.xml
<CustomField>
    <fullName>Candidates_1__c</fullName>
    <label>Candidates 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Setup_Settings__c/fields/Candidates_2__c.field-meta.xml
<CustomField>
    <fullName>Candidates_2__c</fullName>
    <label>Candidates 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Setup_Settings__c/fields/Candidates_3__c.field-meta.xml
<CustomField>
    <fullName>Candidates_3__c</fullName>
    <label>Candidates 3</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Setup_Settings__c/fields/Candidates_4__c.field-meta.xml
<CustomField>
    <fullName>Candidates_4__c</fullName>
    <label>Candidates 4</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Setup_Settings__c/fields/Record_Pages__c.field-meta.xml
<CustomField>
    <fullName>Record_Pages__c</fullName>
    <label>Record Pages</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Setup_Settings__c/fields/Selected_Prompts__c.field-meta.xml
<CustomField>
    <fullName>Selected_Prompts__c</fullName>
    <label>Selected Prompts</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/AISetupAssistantControllerTest.cls
@isTest
public class AISetupAssistantControllerTest {
	
    @testSetup
    static void makeData(){
        AI_Connection__c conn = TestUtility.getConnection('GPTfy', true);
        TestUtility.insertDataExtraction();
        AI_Data_Extraction_Mapping__c master = [SELECT Id FROM AI_Data_Extraction_Mapping__c LIMIT 1];
        String pmtId = AIPromptController.saveAIPrompt(new Map<String, Object>{
            'targetObject' => 'Account', 'aiConnection' => conn.Id, 'promptName' => 'Test Prompt', 'extractionMappingId' => master.Id,
            'selectedType' => 'Text', 'promptCommand' => 'Give a sample response.'
        });
        
        AI_Data_Extraction_Detail__c detail = [SELECT Id FROM AI_Data_Extraction_Detail__c WHERE Object_Name__c = 'ActivityHistory' LIMIT 1];
        delete detail;
        
        AI_Prompt__c pmt = new AI_Prompt__c();
        pmt.Id = pmtId;
        pmt.Pre_Packaged__c = true;
        pmt.Status__c = AIConstants.PMT_STATUS_ACTIVE;
        update pmt;
        
        Account acc = TestUtility.getAccount(true);
        Contact con = TestUtility.getContact(acc.Id, true);
        Case c = TestUtility.getCase(acc.Id, con.Id, true);
    }
    
    @isTest
    static void checkPermissionSetTest(){
        Test.startTest();
        Boolean isAssigned = AISetupAssistantController.checkPermissionSet();
        Test.stopTest();
        System.assert(isAssigned || !isAssigned);
    }
    
    @isTest
    static void getPromptOptionsTest(){
        Test.startTest();
        List<Object> data = AISetupAssistantController.getPromptOptions();
        Test.stopTest();
        System.assert(data != null);
    }
    
    @isTest
    static void getAndUpdateCustomSettings(){
        AI_Prompt__c pmt = [SELECT Id FROM AI_Prompt__c];
        Account acc = [SELECT Id FROM Account];
        Setup_Settings__c settings = Setup_Settings__c.getOrgDefaults();
        settings.Selected_Prompts__c = pmt.Id;
        settings.Record_Pages__c = 'Account';
        settings.Candidates_1__c = JSON.serialize(new Map<String, String>{pmt.Id => acc.Id});
        settings.Candidates_2__c = JSON.serialize(new Map<String, String>{pmt.Id => acc.Id});
        settings.Candidates_3__c = JSON.serialize(new Map<String, String>{pmt.Id => acc.Id});
        settings.Candidates_4__c = JSON.serialize(new Map<String, String>{pmt.Id => acc.Id});
        upsert settings;
        
        Test.startTest();
        List<String> pages = AISetupAssistantController.getSelectedRecordPages();
        AISetupAssistantController.updateSelectedPromptSettings(new List<String>{pmt.Id});
        AISetupAssistantController.updateRecordPageSettings(new List<String>{'Account'});
        AISetupAssistantController.completeDataReview(new List<String>{pmt.Id});
        AISetupAssistantController.checkDataReviewStatus();
        Test.stopTest();
        System.assert(pages != null);
    }
    
    @isTest
    static void startDataReviewTest(){
        AI_Prompt__c pmt = [SELECT Id FROM AI_Prompt__c];
        Test.startTest();
        AISetupAssistantController.startDataReview(new List<String>{pmt.Id});
        AISetupAssistantController.checkDataReviewStatus();
        Test.stopTest();
        Setup_Settings__c settings = Setup_Settings__c.getOrgDefaults();
        System.assert(String.isNotBlank(settings.Candidates_1__c));
    }
    
}