force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/AI_Data_Extraction_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Context Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Connection__c.field-meta.xml
<CustomField>
    <fullName>AI_Connection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AI Model</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the mapping created for the prompt</inlineHelpText>
    <label>Data Context Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Visibility_Condition__c.field-meta.xml
<CustomField>
    <fullName>Visibility_Condition__c</fullName>
    <label>Visibility Condition</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Component__c/AI_Prompt_Component__c.object-meta.xml
<CustomObject>
    <label>Prompt Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Component__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>AI Prompt Components</relationshipLabel>
    <relationshipName>AI_Prompt_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AIPromptBuilderControllerTest.cls
@isTest
public class AIPromptBuilderControllerTest {

	@testSetup
    public static void setupData(){
        TestUtility.insertDataExtraction();
            AI_Prompt__c prompt = TestUtility.getAIPrompt('Test', 'Account', 'Active', false);
            
            AI_Connection__c conn = TestUtility.getConnection('GPTfy', true);
            
            prompt.AI_Connection__c = conn.Id;
            
            List<AI_Data_Extraction_Mapping__c> master = [SELECT Id FROM AI_Data_Extraction_Mapping__c LIMIT 1];
            
            String pmtId = AIPromptController.saveAIPrompt(new Map<String, Object>{ 
                'targetObject' => 'Account', 'aiConnection' => conn.Id, 'promptName' => 'Test Prompt', 'extractionMappingId' => master[0].Id,
                'selectedType' => 'JSON', 'promptCommand' => 'Give a sample response.'
            });
            
            prompt.AI_Data_Extraction_Mapping__c = master[0].Id;
            
            insert prompt;
            
            AI_Prompt_Component__c cmp1 = TestUtility.getPromptComponent(pmtId, master[0].Id, 'Account', false);
            cmp1.AI_Prompt__c = prompt.Id;
            
            insert cmp1;
            
    }
    
    @isTest
    public static void getTabfieldsTest(){
        List<AI_Prompt__c> pmtList = [Select id from AI_Prompt__c where Name='Test' limit 1];
        Map<String,Object> pmtParams = new Map<String,Object>();
        pmtParams.put('Id',pmtList[0].Id);
        pmtParams.put(AIConstants.NAMESPACE+'Visibility_Condition__c','test');
        Test.startTest();
            AIPromptBuilderController.ReturnWrapper retWrap = AIPromptBuilderController.getTabFields(pmtList[0].Id);
        	AIPromptBuilderController.getProfileOptions();
        	AIPromptBuilderController.getTargetFieldOptions('Account');
            AIPromptBuilderController.updatePrompt(pmtParams);
        	Test.stopTest();
        System.assert(retWrap != null);
    }
}