force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Connection__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <inlineHelpText>Used to evoke sensory experience like high for serious answer and low for creativity</inlineHelpText>
    <label>Temperature</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Connection__c/fields/Top_P__c.field-meta.xml
<CustomField>
    <fullName>Top_P__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Top P</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AIAssistantApiCalloutUtilityTest.cls
@isTest
public class AIAssistantApiCalloutUtilityTest {

    @TestSetup
    static void makeData(){
        AI_Connection__c conn = TestUtility.getConnection('GPTfy', true);
        Account testAccount = TestUtility.getAccount(true);
        Contentversion cv = TestUtility.getContentversion('Test', 'Test', 'Test', true);
    }

@IsTest
    static void testProcessFileRequest() {
        AI_Connection__c conn = [SELECT Id, Name, Version__c, Named_Credential__c,Temperature__c,Top_p__c FROM AI_Connection__c WHERE Name = 'GPTfy' LIMIT 1];
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        ContentVersion cv = [SELECT Id,ContentDocumentId FROM ContentVersion WHERE Title = 'Test' LIMIT 1];
        AIAssistantApiCalloutUtility.AssistantWrapper wrap = new AIAssistantApiCalloutUtility.AssistantWrapper();
        wrap.recordId = testAccount.Id;
        wrap.aiModel = conn;
        wrap.extractedData = 'test';
        wrap.cdIds = new List<String>{cv.ContentDocumentId};
        String responseBody = '{"id": "vcId", "status": "succeeded"}';
        Test.setMock(HttpCalloutMock.class, new AIMockCallout(responseBody));
        Test.startTest();
        wrap = AIAssistantApiCalloutUtility.processFileRequest(wrap);
        Test.stopTest();
        System.Assert(wrap != NULL);
    }


@IsTest
    static void testGetAnalyzeResult() {
        AI_Connection__c conn = [SELECT Id, Name, Version__c, Named_Credential__c,Temperature__c,Top_p__c FROM AI_Connection__c WHERE Name = 'GPTfy' LIMIT 1];
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        ContentVersion cv = [SELECT Id,ContentDocumentId FROM ContentVersion WHERE Title = 'Test' LIMIT 1];
        AIAssistantApiCalloutUtility.AssistantWrapper wrap = new AIAssistantApiCalloutUtility.AssistantWrapper();
        wrap.recordId = testAccount.Id;
        wrap.aiModel = conn;
        wrap.extractedData = 'test';
        wrap.threadId = 'test';
        wrap.promptCommand = 'test';
        wrap.vectorStoreId = 'test';
        wrap.uploadedFileId = 'test';
        wrap.assistantId = 'test';
        wrap.messageId = 'test';
        wrap.cdIds = new List<String>{cv.ContentDocumentId};
        String responseBody = '{"data": [{ "content" : [{ "text" : { "value": "This is test result" }}] }], "status": "completed"}';
        Test.setMock(HttpCalloutMock.class, new AIMockCallout(responseBody));
        Test.startTest();
        wrap = AIAssistantApiCalloutUtility.getAnalyzeResult(wrap);
        Test.stopTest();
        System.Assert(wrap != NULL);
    }
}