force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Connection__c.field-meta.xml
<CustomField>
    <fullName>AI_Connection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AI Model</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SnP_SparkChatProcessingClass.cls
global class SnP_SparkChatProcessingClass implements AIProcessingInterface {
	
    global HttpResponse getProcessedResponse(AI_Connection__c aiModel, AI_Prompt__c aiPrompt, String promptCommand, String extractedData){
        String query = promptCommand +' : '+extractedData;
        String requestBody = JSON.serialize(new Map<String, Object>{'query' => query});
        
		//Create a named credential with URL as "https://sparkapiextdev.spglobal.com"
		//Store the named credential Developer name in AI Model's Named Credential field
		//Store the endpoint "/sparkchat" in AI Model's Named Endpoint URL field
        String endpoint = 'callout:'+aiModel.Named_Credential__c+aiModel.EndPoint_URL__c;
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod('POST');
        req.setEndpoint(endpoint);
        //req.setHeader('api-key', ''); //Add the key directly in the Named Credential as part of the custom headers
        req.setHeader('Content-Type', 'application/json');
        req.setBody(requestBody);
        HTTPResponse res = new HTTP().send(req);

		return res;        
    }
    
}