force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Connection__c/fields/Additional_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Additional_Parameters__c</fullName>
    <label>Additional Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Connection__c/fields/Async_Request__c.field-meta.xml
<CustomField>
    <fullName>Async_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Async Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Connection__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>Agentic</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
            <value>
                <fullName>RAG Sync</fullName>
            </value>
            <value>
                <fullName>AI Sync</fullName>
                <isActive>false</isActive>
                <label>AI Sync</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/AI_Data_Extraction_Field__c.object-meta.xml
<CustomObject>
    <label>Data Context Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <label>AI Data Extraction Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <label>Formula</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/AI_Data_Extraction_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Context Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Connection__c.field-meta.xml
<CustomField>
    <fullName>AI_Connection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AI Model</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the mapping created for the prompt</inlineHelpText>
    <label>Data Context Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipLabel>AI Prompts</relationshipLabel>
    <relationshipName>AI_Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Specify the target object for the prompt.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Prompt_Command__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Command__c</fullName>
    <description>Generated based on other selections.</description>
    <label>Prompt Command</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Only prompts with &apos;Active&apos; status will be available to End User. Ensure to Activate the prompt</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Agentic</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <isActive>false</isActive>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/AI_Voice_Configuration__c.object-meta.xml
<CustomObject>
    <label>Voice Configuration</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Configuration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/AI_Model__c.field-meta.xml
<CustomField>
    <fullName>AI_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Model (Processing)</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>Voice Configurations</relationshipLabel>
    <relationshipName>Voice_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/AI_Model_File_Upload__c.field-meta.xml
<CustomField>
    <fullName>AI_Model_File_Upload__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Model (File Upload)</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>Voice Configurations (AI Model (File Upload))</relationshipLabel>
    <relationshipName>Voice_Configurations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/AI_Model_Polling__c.field-meta.xml
<CustomField>
    <fullName>AI_Model_Polling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Model (Polling)</label>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>Voice Configurations (AI Model (Polling))</relationshipLabel>
    <relationshipName>Voice_Configurations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/Maximum_Polling_Counter__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Polling_Counter__c</fullName>
    <label>Maximum Polling Counter</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration__c/fields/Polling_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Polling_Timeframe__c</fullName>
    <label>Polling Timeframe (in mins)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration_Detail__c/AI_Voice_Configuration_Detail__c.object-meta.xml
<CustomObject>
    <label>Voice Configuration Detail</label>
    <nameField>
        <displayFormat>CD-{0000000}</displayFormat>
        <label>Configuration Detail #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice Configuration Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Voice_Configuration_Detail__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>Voice Configuration Details</relationshipLabel>
    <relationshipName>Voice_Configuration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration_Detail__c/fields/AI_Voice_Configuration__c.field-meta.xml
<CustomField>
    <fullName>AI_Voice_Configuration__c</fullName>
    <label>Voice Configuration</label>
    <referenceTo>AI_Voice_Configuration__c</referenceTo>
    <relationshipLabel>Voice Configuration Details</relationshipLabel>
    <relationshipName>Voice_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Voice_Configuration_Detail__c/fields/Related_To_Object__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object__c</fullName>
    <label>Related To Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AudioRecorderControllerTest.cls
@isTest
public class AudioRecorderControllerTest {
	
    @testSetup
    static void makeData(){
        AI_Connection__c conn = TestUtility.getConnection('GPTfy', false);
        conn.Type__c = AIConstants.AI_MODEL_TYPE_VOICE;
        conn.Model__c = 'Chirp';
        insert conn;
        
        Map<String, String> data = new Map<String, String>();
        data.put('recordId', null);
        data.put('mappingName', 'Test Mapping');
        data.put('targetObject', 'ContentVersion');
        data.put('description', 'test desc');
        data.put('objLabel', 'Content Version');
        data.put('aiDataSource', null);
        String masterId = AIDataExtractionController.modifyMaster(data);
        
        AIExtractionFieldMappingController.FieldWrapper cvField = new AIExtractionFieldMappingController.FieldWrapper();
        cvField.fieldName = 'Name';
        cvField.label = 'Name';
        cvField.sendToAI = true;
        cvField.scanForPII = false;
        cvField.fieldType = 'String';
        AIExtractionFieldMappingController.saveFieldMappings(masterId, 'ContentVersion', new List<AIExtractionFieldMappingController.FieldWrapper>{cvField});
        
        //TestUtility.insertDataExtraction();
        //List<AIExtractionFieldMappingController.PicklistAttributeWrapper> formula = AIExtractionFieldMappingController.validateFormula('Account','STRING','Name');
        List<AI_Data_Extraction_Field__c> dataExtractionFields = [SELECT id, formula__c FROM AI_Data_Extraction_Field__c where object__c = 'ContentVersion' AND Type__c ='FIELD'];
        dataExtractionFields[0].formula__c = 'Title';
        dataExtractionFields[0].Field_Type__c = 'STRING';
        update dataExtractionFields;
        AI_Data_Extraction_Mapping__c master = [SELECT Id FROM AI_Data_Extraction_Mapping__c LIMIT 1];
        String pmtId = AIPromptController.saveAIPrompt(new Map<String, Object>{
            'targetObject' => 'ContentVersion', 'aiConnection' => conn.Id, 'promptName' => 'Test Prompt', 'extractionMappingId' => master.Id,
            'selectedType' => 'JSON', 'promptCommand' => 'Give a sample response.'
        }); 
        
        AI_Prompt__c pmt = new AI_Prompt__c();
        pmt.Id = pmtId;
        pmt.Status__c = AIConstants.PMT_STATUS_ACTIVE;
        pmt.Prompt_Command__c = 'Give a sample response.';
        update pmt;
        
        AIVoiceConfigurationController.ConfigurationWrapper wrap = AIVoiceConfigurationController.getConfigurationDetails();
        wrap.duration = 1;
        wrap.aiModelId = conn.Id;
        AIVoiceConfigurationController.updateConfiguration(JSON.serialize(wrap));
        
        
        TestUtility.getAccount(true);
        ContentVersion cv = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = false
        );
        insert cv;  
    }
    
    @isTest
    static void createContentDocumentLinkTest(){
        ContentVersion cv = [SELECT Id, ContentDocumentId FROM ContentVersion LIMIT 1];
        Account a = [SELECT Id FROM Account LIMIT 1];
        AI_Prompt__c pmt = [SELECT Id FROM AI_Prompt__c LIMIT 1];
        List<AI_Voice_Configuration__c> lstOfConfigs = [SELECT Id, Async_Request__c,AI_Model__c,AI_Model_File_Upload__c,Maximum_Polling_Counter__c FROM AI_Voice_Configuration__c where AI_Model__c != NULL];
        AI_Voice_Configuration_Detail__c voiceDetail = new AI_Voice_Configuration_Detail__c(Related_To_Object__c='Account',
                                                                                           AI_Prompt__c=pmt.Id,
                                                                                           AI_Voice_Configuration__c=lstOfConfigs.get(0).Id);
        insert voiceDetail;
        Test.startTest();
       // String respBody = '{"results": [{"alternatives" : [{"transcript" : "Test"}]}]}';
        String respBody = '{ "response" : { "results": [{ "channelTag": 1, "alternatives" : [{"transcript" : "Test" }] }] } }';
        Test.setMock(HttpCalloutMock.class, new AIMockCallout(respBody));
        AudioRecorderController.createContentDocumentLink(cv.Id, a.Id, false);
        AudioRecorderController.isUserAuthorized();
        Test.stopTest();
        
        ContentDocumentLink contentlink = [SELECT Id FROM ContentDocumentLink WHERE ContentDocumentId =:cv.ContentDocumentId LIMIT 1];
        System.assertNotEquals(null, contentlink, 'ContentDocumentLink should be created.');
    }
    
    @isTest
    static void testSyncIOSTest(){
        ContentVersion cv = [SELECT Id, ContentDocumentId FROM ContentVersion LIMIT 1];
        Account a = [SELECT Id FROM Account LIMIT 1];
        Test.startTest();
       // String respBody = '{"results": [{"alternatives" : [{"transcript" : "Test"}]}]}';
        String respBody = '{ "transcript" : "Test" }';
        Test.setMock(HttpCalloutMock.class, new AIMockCallout(respBody));
        AudioRecorderController.createContentDocumentLink(cv.Id, a.Id, true);
        Test.stopTest();
        
        ContentDocumentLink contentlink = [SELECT Id FROM ContentDocumentLink WHERE ContentDocumentId =:cv.ContentDocumentId LIMIT 1];
        System.assertNotEquals(null, contentlink, 'ContentDocumentLink should be created.');
    }
    
     @isTest
    static void audioProcessAsyncTest(){
        ContentVersion cv = [SELECT Id, ContentDocumentId FROM ContentVersion LIMIT 1];
        Account a = [SELECT Id FROM Account LIMIT 1];
        AI_Connection__c con = [SELECT Id, Name, Type__c, Additional_Parameters__c, Model__c FROM AI_Connection__c];
        con.Additional_Parameters__c = ' { "privateKeyFileId" : "'+cv.ContentDocumentId+'", "clientId": "testclientId", "authUrl": "https//www.gptfy.ai" ,"tokenUrl": "tokenUrl" } ';
        update con;
        List<AI_Voice_Configuration__c> lstOfConfigs = [SELECT Id, Async_Request__c,AI_Model__c,AI_Model_File_Upload__c FROM AI_Voice_Configuration__c where AI_Model__c != NULL];
        lstOfConfigs.get(0).Async_Request__c = true;
        lstOfConfigs.get(0).AI_Model_File_Upload__c = con.Id;
        lstOfConfigs.get(0).AI_Model_Polling__c = con.Id;
        update lstOfConfigs;
        Test.startTest();
        String respBody = '{ "name":"JobIdName", "mediaLink":"test.com", "response" : { "results": [{ "alternatives" : [{"transcript" : "Test" }] }] } }';
        Test.setMock(HttpCalloutMock.class, new AIMockCallout(respBody));
        AudioRecorderController.createContentDocumentLink(cv.Id, a.Id, false);
        Test.stopTest();
        
        ContentDocumentLink contentlink = [SELECT Id FROM ContentDocumentLink WHERE ContentDocumentId =:cv.ContentDocumentId LIMIT 1];
        System.assertNotEquals(null, contentlink, 'ContentDocumentLink should be created.');
    }
    
    @isTest
    static void audioProcessAsyncCounterTest(){
        ContentVersion cv = [SELECT Id, ContentDocumentId FROM ContentVersion LIMIT 1];
        AI_Prompt__c pmt = [SELECT Id FROM AI_Prompt__c LIMIT 1];
        Account a = [SELECT Id FROM Account LIMIT 1];
        AI_Connection__c con = [SELECT Id, Name, Type__c, Additional_Parameters__c, Model__c FROM AI_Connection__c];
        con.Additional_Parameters__c = ' { "privateKeyFileId" : "'+cv.ContentDocumentId+'", "clientId": "testclientId", "authUrl": "https//www.gptfy.ai" ,"tokenUrl": "tokenUrl" } ';
        con.Model__c = AIConstants.KENSHO_VOICE_MODEL;
        
        update con;
        List<AI_Voice_Configuration__c> lstOfConfigs = [SELECT Id, Async_Request__c,AI_Model__c,AI_Model_File_Upload__c,Maximum_Polling_Counter__c FROM AI_Voice_Configuration__c where AI_Model__c != NULL];
        lstOfConfigs.get(0).Async_Request__c = true;
        lstOfConfigs.get(0).AI_Model_Polling__c = con.Id;
        lstOfConfigs.get(0).Maximum_Polling_Counter__c = 2;
        lstOfConfigs.get(0).AI_Model_File_Upload__c = con.Id;
        lstOfConfigs.get(0).Polling_Timeframe__c = 1;
        update lstOfConfigs;
        AI_Voice_Configuration_Detail__c voiceDetail = new AI_Voice_Configuration_Detail__c(Related_To_Object__c='Account',
                                                                                           AI_Prompt__c=pmt.Id,
                                                                                           AI_Voice_Configuration__c=lstOfConfigs.get(0).Id);
        insert voiceDetail;
        String respBody = '{ "fileUrl": "testurl", "name":"JobIdName", "mediaLink":"test.com", "results": [{ "channelTag": 1,"alternatives" : [{"transcript" : "" }] }]  }';
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AIMockCallout(respBody));
        AudioRecorderController.createContentDocumentLink(cv.Id, a.Id, false);
        Test.stopTest();
        
        ContentDocumentLink contentlink = [SELECT Id FROM ContentDocumentLink WHERE ContentDocumentId =:cv.ContentDocumentId LIMIT 1];
        System.assertNotEquals(null, contentlink, 'ContentDocumentLink should be created.');
    }
    
}