force-app/main/default/objects/AI_Connection__c/AI_Connection__c.object-meta.xml
<CustomObject>
    <description>Required for BYOK customers. Will store information about the AI service, endpoint, connector class(interface class, if any), and ‘Named Credential’ name.</description>
    <label>AI Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/AI_Model_File_Processing__c.field-meta.xml
<CustomField>
    <fullName>AI_Model_File_Processing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Model - File Processing</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AI_Connection__c.Type__c</field>
            <operation>equals</operation>
            <value>File</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AI_Connection__c</referenceTo>
    <relationshipLabel>Prompts (AI Model - File Processing)</relationshipLabel>
    <relationshipName>Prompts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Include_Files__c.field-meta.xml
<CustomField>
    <fullName>Include_Files__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Files</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Prompt_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Request_Id__c</fullName>
    <label>Prompt Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Only prompts with &apos;Active&apos; status will be available to End User. Ensure to Activate the prompt</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Response__c/AI_Response__c.object-meta.xml
<CustomObject>
    <label>Security Audit</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Audit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Response__c/fields/AI_Processed_Data_PII_Added__c.field-meta.xml
<CustomField>
    <fullName>AI_Processed_Data_PII_Added__c</fullName>
    <inlineHelpText>Response from AI</inlineHelpText>
    <label>AI Processed Data(PII Added)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Prompt that is used</inlineHelpText>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipName>AI_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Data Extracted</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Errored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AIPromptProcessingWebService.cls
@RestResource(urlMapping='/v1/executePrompt/*')
global with sharing class AIPromptProcessingWebService {
    
    /**
     * Executes a request and returns a ResponseWrapper.
     * This method is designed to perform some global operation,
     * such as making an API request, and encapsulates the response
     * in a custom ResponseWrapper object.
     *
     * @return A ResponseWrapper containing the result of the request.
     *         The ResponseWrapper typically includes information such as
     *         the response status, data, and any additional details.
     */

	@HttpPost
    global static ResponseWrapper runRequest(){
        
        ResponseWrapper response = new ResponseWrapper();
        response.status = 'Error';
        response.statusCode = 400;
		response.message = AIConstants.REQUEST_FAILED;
        
        RequestWrapper request = new RequestWrapper();
        RestRequest req = RestContext.request; 
        try{
            String jsonBody = req.requestBody.toString();
            if(String.isNotBlank(jsonBody)){
                request = (RequestWrapper)JSON.deserializeStrict(jsonBody, RequestWrapper.class);
            }
        }catch(Exception e){
            response.message = AIConstants.INCORRECT_JSON;
            GPTfyException.log(e, 'GPTfy', '', 'AIPromptProcessingWebService', 'runRequest', '');
            return response;
        }

        if(request != null){
            if(String.isBlank(request.promptRequestId)){
            	response.message = AIConstants.PMT_REQ_ID_NOT_FOUND;
            }else if(String.isBlank(request.recordId)){
                response.message = AIConstants.REC_ID_NOT_FOUND;
            }else{
                List<AI_Prompt__c> lstOfPrompts = [SELECT Id FROM AI_Prompt__c 
                                                   WHERE Prompt_Request_Id__c =:request.promptRequestId 
                                                   AND Status__c =:AIConstants.PMT_STATUS_ACTIVE
                                                   LIMIT 1];
                if(lstOfPrompts != null && !lstOfPrompts.isEmpty()){
                    AI_Prompt__c pmt = lstOfPrompts.get(0);
                    String objName;
                    try{
                        objName = Id.valueOf(request.recordId).getSObjectType().getDescribe().getName();
                    }catch(Exception e){
                        GPTfyException.log(e, 'GPTfy', '', 'AIPromptProcessingWebService', 'runRequest', '');
                    }
                    if(String.isNotBlank(objName)){
                        String recId = request.recordId;
                        String query = 'SELECT Id FROM '+String.escapeSingleQuotes(objName)+' WHERE Id =:recId LIMIT 1 ';
                        List<sObject> lst = Database.query(query);
                        if(lst != null && !lst.isEmpty()){
                            response = invokeCallout(request, response,pmt.Id);
                        }else{
                            response.message = AIConstants.REC_ID_DOES_NOT_EXISTS;
                        }
                    }else{ 
                        response.message = AIConstants.INCORRECT_REC_ID;
                    }
                }else{
                    response.message = AIConstants.NO_ACTIVE_PMT_FOUND;
                }
            }
        }else{
            response.message = AIConstants.EMPTY_REQ_BODY;
        }
        return response;
    }
    
    public static ResponseWrapper invokeCallout(RequestWrapper request, ResponseWrapper response, String promptId){
        try{
            AI_Prompt__c aiPrompt = AIPromptSelector.getAIPromptById(promptId);
            if(!Test.isRunningTest()){
            	if(!ChatGPTUtills.checkLicensePlanActive(System.Label.LICENSES_STARTER_PLAN)){
            		throw new ChatGPTUtills.ApplicationException(String.format(System.Label.LICENESES_PLAN_ERROR_MESSAGE,new List<String> { System.Label.LICENSES_PRO_PLAN }));
            	}
            }
            AI_Response__c resp;
            if(aiPrompt.Include_Files__c == true && AIConstants.RESPONSES_API_MODEL.contains(aiPrompt.AI_Model_File_Processing__r.Model__c)){
                resp = ChatGPTUtills.processResponsesFileRequest(promptId, request.recordId,request.customPromptCommand, new AI_Response__c());
            }else{
                resp = ChatGPTUtills.initiateGPT(request.recordId, promptId, request.customPromptCommand, null, false);
            }
            if(resp != null){
                response.responseId = resp.Id;
                response.responseBody = resp.AI_Processed_Data_PII_Added__c;
                response.status = resp.Status__c;
                response.statusCode = 200;
                response.message = resp.Message__c;
            }
            
        }catch(Exception e){
            response.message = e.getMessage(); 
            response.statusCode = 500;
        }
        return response;
    }
    
    global class RequestWrapper{
        global String promptRequestId{get;set;}
        global String recordId{get;set;}
        global String customPromptCommand{get;set;}
    }
    
    global class ResponseWrapper{
        global String responseId{get;set;}
        global String responseBody{get;set;}
        global String status{get;set;}
        global Integer statusCode{get;set;}
        global String message{get;set;}
    }
    
}