force-app/main/default/objects/Account_Config__b/Account_Config__b.object-meta.xml
<CustomObject>
    <label>Account Config</label>
    <pluralLabel>Account Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account_Config__b/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Configs</relationshipLabel>
    <relationshipName>Account_Configs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BigObjectResearch.cls
public class BigObjectResearch {
    public static void createRecord(String accountId){
        Account_Config__b obj = new Account_Config__b();
        obj.Account_Name__c = 'Test Inserted';
        obj.Account__c = accountId;
        System.debug(database.insertImmediate(obj));
        System.debug([SELECT Id FROM Account_Config__b].size());
        System.debug([SELECT Account_Name__c FROM Account_Config__b]);
    }
    public static void updateRecord(String accountId){
        Account_Config__b obj = new Account_Config__b();
        obj.Account_Name__c = 'Test Updated';
        obj.Account__c = accountId;
        System.debug(database.insertImmediate(obj));
        System.debug([SELECT Id FROM Account_Config__b].size());
        System.debug([SELECT Account_Name__c FROM Account_Config__b]);
    }
    public static void deleteRecord(String accountId){
       	database.deleteImmediate([SELECT Account__c FROM Account_Config__b WHERE Account__c = :accountId]);
        System.debug([SELECT Id FROM Account_Config__b].size());
        System.debug([SELECT Account_Name__c FROM Account_Config__b]);
    }
}