force-app/main/default/objects/AI_Feedback__c/AI_Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Feedback #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Feedback__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partial Response</fullName>
            </value>
            <value>
                <fullName>Made-up Response</fullName>
            </value>
            <value>
                <fullName>Irrelevant Response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Feedback__c/fields/Security_Audit__c.field-meta.xml
<CustomField>
    <fullName>Security_Audit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Security Audit</label>
    <referenceTo>AI_Response__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Feedback__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Like</fullName>
            </value>
            <value>
                <fullName>Dislike</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/AI_Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <label>AI Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt__c/fields/Auto_Refresh_Duration__c.field-meta.xml
<CustomField>
    <fullName>Auto_Refresh_Duration__c</fullName>
    <label>Auto Refresh Duration (In Hours)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/How_it_works__c.field-meta.xml
<CustomField>
    <fullName>How_it_works__c</fullName>
    <label>How it Works?</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Specify the target object for the prompt.</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Prompt_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Request_Id__c</fullName>
    <label>Prompt Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Only prompts with &apos;Active&apos; status will be available to End User. Ensure to Activate the prompt</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Agentic</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <isActive>false</isActive>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Prompt_Element__c/AI_Prompt_Element__c.object-meta.xml
<CustomObject>
    <label>Prompt Element</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Prompt Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Prompt_Element__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Prompt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AI_Prompt__c.Type__c</field>
            <operation>notEqual</operation>
            <value>Canvas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>Prompt Elements (Prompt)</relationshipLabel>
    <relationshipName>AI_Child_Prompt_Elements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Element__c/fields/AI_Summary_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Summary_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary Prompt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AI_Prompt__c.Type__c</field>
            <operation>notEqual</operation>
            <value>Canvas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipLabel>Prompt Elements (Summary Prompt)</relationshipLabel>
    <relationshipName>Summary_Prompt_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Element__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Prompt_Element__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1/3 Column</fullName>
                <default>true</default>
                <label>1/3 Column</label>
            </value>
            <value>
                <fullName>2/3 Column</fullName>
            </value>
            <value>
                <fullName>3/3 Column</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Response__c/AI_Response__c.object-meta.xml
<CustomObject>
    <label>Security Audit</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Audit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Response__c/fields/AI_Parent_Response__c.field-meta.xml
<CustomField>
    <fullName>AI_Parent_Response__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Parent Response</label>
    <referenceTo>AI_Response__c</referenceTo>
    <relationshipLabel>Security Audits (AI Parent Response)</relationshipLabel>
    <relationshipName>Parent_Security_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/AI_Processed_Data_PII_Added__c.field-meta.xml
<CustomField>
    <fullName>AI_Processed_Data_PII_Added__c</fullName>
    <inlineHelpText>Response from AI</inlineHelpText>
    <label>AI Processed Data(PII Added)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/AI_Prompt__c.field-meta.xml
<CustomField>
    <fullName>AI_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Prompt that is used</inlineHelpText>
    <label>AI Prompt</label>
    <referenceTo>AI_Prompt__c</referenceTo>
    <relationshipName>AI_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Completion_Tokens__c.field-meta.xml
<CustomField>
    <fullName>Completion_Tokens__c</fullName>
    <inlineHelpText>Tokens generated by the AI model as part of its response</inlineHelpText>
    <label>Completion Tokens</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/How_it_works__c.field-meta.xml
<CustomField>
    <fullName>How_it_works__c</fullName>
    <label>How it works</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Is_Canvas_Response__c.field-meta.xml
<CustomField>
    <fullName>Is_Canvas_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Canvas Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Prompt_Element_Details__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Element_Details__c</fullName>
    <label>Prompt Element Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Prompt_Tokens__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Tokens__c</fullName>
    <inlineHelpText>Initial input text  provided to the AI model to generate a response.</inlineHelpText>
    <label>Prompt Tokens</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Data Extracted</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Errored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Response__c/fields/Time_Saved_Seconds__c.field-meta.xml
<CustomField>
    <fullName>Time_Saved_Seconds__c</fullName>
    <description>Saving is calculated based on 8 tokens are read per second.</description>
    <formula>If(Prompt_Tokens__c-Completion_Tokens__c &gt;0,CEILING((Prompt_Tokens__c-Completion_Tokens__c)/IF(NOT(ISBLANK(AI_Prompt__c)) &amp;&amp; AI_Prompt__r.Time_Saved_Coefficient__c &gt; 0, AI_Prompt__r.Time_Saved_Coefficient__c, 8)),CEILING((Completion_Tokens__c-Prompt_Tokens__c)/IF(NOT(ISBLANK(AI_Prompt__c)) &amp;&amp; AI_Prompt__r.Time_Saved_Coefficient__c &gt; 0, AI_Prompt__r.Time_Saved_Coefficient__c, 8)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Saved(Seconds)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AICanvasController.cls
/**
 * @description: 
 *   AICanvasController provides Lightning-enabled methods to retrieve AI Canvas template 
 *   details, their components, and associated AI prompts from the backend. 
 *   This is used to drive UI experiences for dynamic AI canvas rendering.
 *                      
 * @author            : Piyush Chourasia
 * @group             : Plumcloud Labs
 * @last modified on  : 04-09-2025
 * @last modified by  : Piyush Chourasia
 **/
public with sharing class AICanvasController {

    public static final String NAMESPACE = AIPromptController.getNameSpace();

    /**
     * @description:
     *   Retrieves details of the winning AI Canvas Template for a given record ID and object type.
     *
     * @param recordId       - The record ID used for current record
     * @param objectApiName  - The API name of the object (e.g., Account, Case)
     * @return CanvasTemplateDetails if a matching template is found, else null
     */
    @AuraEnabled
    public static Boolean isCanvasUser(){
        try{
            List<String> validPermSets = new List<String>{'SGPT_Admin', 'SGPT_User', 'SGPT_Portal_User'};
            String l_namespace = NAMESPACE;
            if(String.isNotBlank(l_namespace) && l_namespace.endsWithIgnoreCase('__')){
                l_namespace = l_namespace.removeEndIgnoreCase('__');
            }
            List<PermissionSetAssignment> psas = [SELECT Id FROM PermissionSetAssignment 
                                                WHERE PermissionSet.Name IN :validPermSets 
                                                AND AssigneeId = :UserInfo.getUserId()
                                                AND PermissionSet.NamespacePrefix =:l_namespace];
            if(psas != null && !psas.isEmpty()){
                return true;
            }
            return false;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * @description:
     *   Retrieves details of the winning AI Canvas Template for a given record ID and object type.
     *
     * @param recordId       - The record ID used for current record
     * @param objectApiName  - The API name of the object (e.g., Account, Case)
     * @return CanvasTemplateDetails if a matching template is found, else null
     * @Jira V2-6591
     */
    @AuraEnabled
    public static CanvasDetails getPromptElementsWithPrompts(String promptId, String recordId, String objectApiName, String parentAIResponse,Boolean notInitialLoad) {
        try {
            List<PromptElement> promptElementsWrap = new List<PromptElement>();
            List<PromptDetail> promptDetailsWrap = new List<PromptDetail>();
            List<AIDataExtractionController.PicklistWrapper> picklistWrapper = 
                AIPromptController.getPickListValues(GPTfyConsoleController.NAMESPACE+'AI_Feedback__c', GPTfyConsoleController.NAMESPACE+'Category__c');
            Set<Id> promptIds = new Set<Id>();
            String userSignature = AICanvasService.getUserSignature();
            AI_Response__c parentResponse;
            if(!String.isEmpty(parentAIResponse)){
                parentResponse = AICanvasService.fetchSecurityAuditRecord(parentAIResponse,recordId);
                promptId = parentResponse.AI_Prompt__c;
            }else if(promptId == null || promptId == ''){
                AI_Prompt__c winnerPrompt = AICanvasService.fetchWinnerPrompt(recordId, objectApiName);
                if(winnerPrompt == null){
                    return null;
                }
                promptId = winnerPrompt.Id;
            }
            if(parentResponse == null && promptId != null && notInitialLoad != null && notInitialLoad == false){
                parentResponse = AICanvasService.fetchSecurityAuditRecordByPromptId(promptId,recordId);
            }

            AI_Prompt__c prompt = AICanvasService.getPromptDetails(recordId, objectApiName,promptId);

            if(prompt == null){
                return null;
            }
            if(!String.isEmpty(objectApiName) && objectApiName != prompt.Object__c){
                return null;
            }
            
            String emailActionName = AICanvasService.getEmailActionName(objectApiName);

            if(parentResponse != null){
                for(AI_Response__c resp : parentResponse.Parent_Security_Audits__r){
                    if(!String.isEmpty(resp.Prompt_Element_Details__c)){
                        PromptElement pElement = (PromptElement)JSON.deserialize(resp.Prompt_Element_Details__c, PromptElement.class);
                        promptElementsWrap.add(pElement);
                        promptIds.add(pElement.prompt);
                        if(pElement.summaryPrompt != null){
                            promptIds.add(pElement.summaryPrompt);
                        }
                    }
                }
            }
            if(parentResponse == null || promptElementsWrap.isEmpty()){
                List<AI_Prompt_Element__c> promptElements = AICanvasService.getPromptElementsByPromptId(promptId);

                if(!promptElements.isEmpty()){
                    for(AI_Prompt_Element__c element : promptElements){
                        promptIds.add(element.AI_Prompt__c);
                        if(element.AI_Summary_Prompt__c != null){
                            promptIds.add(element.AI_Summary_Prompt__c);
                        }
                        promptElementsWrap.add(new PromptElement(element));
                    }
                }
            }

            if (promptIds.isEmpty()) {
                return null;
            }

            // Fetch all prompts referenced in the components
            List<AI_Prompt__c> prompts = AICanvasService.fetchPrompts(promptIds);

            for (AI_Prompt__c prmt : prompts) {
                promptDetailsWrap.add(new PromptDetail(prmt));
            }

            if (promptElementsWrap.isEmpty() && promptDetailsWrap.isEmpty()) {
                return null;
            }

            return new CanvasDetails(userSignature,emailActionName,new PromptDetail(prompt),promptElementsWrap,promptDetailsWrap,picklistWrapper);
        } catch (Exception ex) {
            // Return a controlled error for front-end handling
            throw new AuraHandledException(ex.getMessage());
        }
    }
    /**
     * @description:
     *   Retrieves details of the winning AI Canvas Template for a given record ID and object type.
     *
     * @param recordId       - The record ID used for current record
     * @param objectApiName  - The API name of the object (e.g., Account, Case)
     * @return CanvasTemplateDetails if a matching template is found, else null
     * @Jira V2-6591
     */
    @AuraEnabled
    public static AI_Response__c getSecurityAudit(String promptId, String recordId,Boolean notInitialLoad, String responseId) {
        try {
            AI_Response__c aiResponse = new AI_Response__c();
            if(notInitialLoad == true){
                aiResponse = getNewAIResponse(recordId,promptId);
            }else if(!String.isBlank(responseId) && responseId.length() > 0){
                aiResponse = AICanvasService.fetchSecurityAuditRecord(responseId,recordId);
            }else{
                aiResponse = AICanvasService.fetchSecurityAuditRecordByPromptId(promptId,recordId);
            }
            if(aiResponse == null){
                aiResponse = getNewAIResponse(recordId,promptId);
            }
            if(aiResponse != null){
                return aiResponse;
            }
            return null;
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }
    private static AI_Response__c getNewAIResponse(String recordId, String promptId){
        AI_Response__c aiResponse = new AI_Response__c();
        aiResponse.Record_Id__c = recordId;
        aiResponse.Status__c = AIConstants.RESP_STATUS_INPROGRESS;
        aiResponse.Is_Canvas_Response__c = true;
        aiResponse.AI_Prompt__c = promptId;
            
        List<SObject> records = FLSCheck.getInstance().insertDML(new List<AI_Response__c>{aiResponse});

        return AICanvasService.fetchSecurityAuditRecord(records.get(0).Id,recordId);
    }
    @AuraEnabled
    public static AI_Response__c updateParentAIResponse(String parentAIResponse, String childAiResponseIds, String recordId){
        try {
            Set<Id> childResponseIds = (Set<Id>)JSON.deserialize(childAiResponseIds, Set<Id>.class);
            
            List<AI_Response__c> aiResponses = AICanvasService.fetchAIResponses(childResponseIds, recordId);
            List<AI_Response__c> responseToBeUpdated = new List<AI_Response__c>();
            Integer promptToken = 0;
            Integer completionToken = 0;

            for(AI_Response__c resp : aiResponses){
                resp.AI_Parent_Response__c = parentAIResponse;
                completionToken+= (resp.Completion_Tokens__c != null ? Integer.valueOf(resp.Completion_Tokens__c) : 0);
                promptToken+= (resp.Prompt_Tokens__c != null ? Integer.valueOf(resp.Prompt_Tokens__c) : 0);
                responseToBeUpdated.add(resp);
            }
            responseToBeUpdated.add(new AI_Response__c(
                    Id = parentAIResponse, 
                    Completion_Tokens__c = completionToken, 
                    Prompt_Tokens__c = promptToken, 
                    Status__c = AIConstants.RESP_STATUS_PROCESSED,
                    Is_Canvas_Response__c = true));
            
            FLSCheck.getInstance().upsertDML(responseToBeUpdated);
            
            AI_Response__c aiResponse = AICanvasService.fetchSecurityAuditRecord(parentAIResponse,recordId);

            if(aiResponse != null){
                return aiResponse;
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * @description:
     *   Inner class that wraps component details of a Canvas Template.
     */
    public class SecurityAudit{
        @AuraEnabled public String Id;
        @AuraEnabled public String name;
        @AuraEnabled public String responseBody;
        @AuraEnabled public String feedbackType;
        @AuraEnabled public String message;
        @AuraEnabled public String howItWorks;
        @AuraEnabled public Double timeSaved;

        /**
         * @description:
         *  Constructor to convert and populate fields from the internal response structure.
         */
        public SecurityAudit(AI_Response__c aIResponse) {
            this.Id = aIResponse.Id;
            this.responseBody = aIResponse.AI_Processed_Data_PII_Added__c;
            this.name = aIResponse.Name;
            this.feedbackType = (aIResponse.Feedbacks__r != null && aIResponse.Feedbacks__r.size() > 0) ? aIResponse.Feedbacks__r[0].Type__c : '';
            this.message = aIResponse.Message__c;
            this.howItWorks = aIResponse.How_it_works__c;
            this.timeSaved = aIResponse.Time_Saved_Seconds__c;
        }
    }
    /**
     * @description:
     *   Inner class representing prompt metadata linked to the template.
     */
    public class CanvasTemplatePrompt {
        @AuraEnabled public String Id;
        @AuraEnabled public String promptRequestId;
        @AuraEnabled public String name;
        @AuraEnabled public Integer autoRefreshDuration;


        public CanvasTemplatePrompt(AI_Prompt__c templatePrompt) {
            this.Id = templatePrompt.Id;
            this.promptRequestId = templatePrompt.Prompt_Request_Id__c;
            this.name = templatePrompt.Name;
            this.autoRefreshDuration = Integer.valueOf(templatePrompt.Auto_Refresh_Duration__c);
        }
    }

     /**
     * @description:
     *   Inner class that wraps component details of a Canvas Template.
     */
    public class PromptElement {
        @AuraEnabled public String Id;
        @AuraEnabled public String prompt;
        @AuraEnabled public String summaryPrompt;
        @AuraEnabled public Integer sequence;
        @AuraEnabled public String width;
        @AuraEnabled public Integer height;
        @AuraEnabled public String cardIcon;
        @AuraEnabled public String parentPrompt;
        @AuraEnabled public String response;
        @AuraEnabled public Boolean inheritPromptSecurity;

        public PromptElement(AI_Prompt_Element__c promptEle) {
            this.Id = promptEle.Id;
            this.prompt = promptEle.AI_Prompt__c;
            this.summaryPrompt = promptEle.AI_Summary_Prompt__c;
            this.sequence = Integer.valueOf(promptEle.Sequence__c);
            this.width = promptEle.Width__c;
            this.cardIcon = promptEle.Icon__c;
            this.height = Integer.valueOf(promptEle.Height__c);
            this.parentPrompt = promptEle.AI_Parent_Prompt__c;
            this.inheritPromptSecurity = promptEle.Inherit_Prompt_Security__c;
        }
        public PromptElement setResponse(String response){
            this.response = response;
            return this;
        }
    }

    /**
     * @description:
     *   Inner class representing prompt metadata linked to the template.
     */
    public class PromptDetail {
        @AuraEnabled public String Id;
        @AuraEnabled public String promptRequestId;
        @AuraEnabled public String name;
        @AuraEnabled public Integer autoRefreshDuration;

        public PromptDetail(AI_Prompt__c prompt) {
            this.Id = prompt.Id;
            this.promptRequestId = prompt.Prompt_Request_Id__c;
            this.name = prompt.Name;
            this.autoRefreshDuration = Integer.valueOf(prompt.Auto_Refresh_Duration__c);
        }
    }
    /**
     * @description:
     *   Wrapper for combining Canvas Template Components and associated Prompts in one object.
     */
    public class CanvasDetails {
        @AuraEnabled public String userSignature;
        @AuraEnabled public String emailActionName;
        @AuraEnabled public PromptDetail prompt;
        @AuraEnabled public List<PromptElement> promptElements;
        @AuraEnabled public List<PromptDetail> promptDetails;
        @AuraEnabled public List<AIDataExtractionController.PicklistWrapper> picklistWrapper;
        @AuraEnabled public String namespace;

        public CanvasDetails(
                String userSignature,
                String emailActionName,
                PromptDetail prompt,
                List<PromptElement> promptElements, 
                List<PromptDetail> promptDetails,
                List<AIDataExtractionController.PicklistWrapper> picklistWrapper) {
            this.userSignature = userSignature;
            this.emailActionName = emailActionName;
            this.prompt = prompt;
            this.promptElements = promptElements;
            this.promptDetails = promptDetails;
            this.picklistWrapper = picklistWrapper;
            this.namespace = AIConstants.NAMESPACE;
        }
    }
}