force-app/main/default/objects/AI_Data_Extraction_Detail__c/AI_Data_Extraction_Detail__c.object-meta.xml
<CustomObject>
    <label>Data Context Detail</label>
    <nameField>
        <label>Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <label>AI Data Extraction Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Object_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Object_Hierarchy__c</fullName>
    <label>Object Hierarchy</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <label>Order By</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Parent_Detail__c.field-meta.xml
<CustomField>
    <fullName>Parent_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Detail</label>
    <referenceTo>AI_Data_Extraction_Detail__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/RelationshipField__c.field-meta.xml
<CustomField>
    <fullName>RelationshipField__c</fullName>
    <label>Relationship Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/RelationshipName__c.field-meta.xml
<CustomField>
    <fullName>RelationshipName__c</fullName>
    <label>Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Running_Index__c.field-meta.xml
<CustomField>
    <fullName>Running_Index__c</fullName>
    <label>Running Index</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Where_Clause__c.field-meta.xml
<CustomField>
    <fullName>Where_Clause__c</fullName>
    <inlineHelpText>Where Clause</inlineHelpText>
    <label>Where Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/AI_Data_Extraction_Field__c.object-meta.xml
<CustomObject>
    <label>Data Context Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <label>AI Data Extraction Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Anonymize_With__c.field-meta.xml
<CustomField>
    <fullName>Anonymize_With__c</fullName>
    <label>Anonymize With</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PersonF{n}</fullName>
            </value>
            <value>
                <fullName>PersonL{n}</fullName>
            </value>
            <value>
                <fullName>PersonFull{n}</fullName>
            </value>
            <value>
                <fullName>removed{n}@removed.com</fullName>
            </value>
            <value>
                <fullName>Street{n}</fullName>
            </value>
            <value>
                <fullName>City{n}</fullName>
            </value>
            <value>
                <fullName>State{n}</fullName>
            </value>
            <value>
                <fullName>Country{n}</fullName>
            </value>
            <value>
                <fullName>Phone{n}</fullName>
            </value>
            <value>
                <fullName>Product{n}</fullName>
            </value>
            <value>
                <fullName>Company{n}</fullName>
            </value>
            <value>
                <fullName>{n}</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <label>Formula</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Masking_Scope__c.field-meta.xml
<CustomField>
    <fullName>Masking_Scope__c</fullName>
    <label>Masking Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entire Value</fullName>
            </value>
            <value>
                <fullName>Specific Patterns</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Scan_for_PII__c.field-meta.xml
<CustomField>
    <fullName>Scan_for_PII__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scan for PII</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Send_To_AI__c.field-meta.xml
<CustomField>
    <fullName>Send_To_AI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send To AI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/AI_Data_Extraction_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Context Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/AI_Data_Source__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>API Data Connection</label>
    <referenceTo>AI_Data_Source__c</referenceTo>
    <relationshipLabel>Data Context Mappings</relationshipLabel>
    <relationshipName>Data_Context_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/Apex_Security_Layer__c.field-meta.xml
<CustomField>
    <fullName>Apex_Security_Layer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apex (Security Layer)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AI_Security_Filters__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Apex</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AI_Security_Filters__c</referenceTo>
    <relationshipLabel>Data Context Mappings</relationshipLabel>
    <relationshipName>Data_Context_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <formula>(&quot;AI_Data_Extraction_Mapping__c&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Target Object</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Data_Source__c/AI_Data_Source__c.object-meta.xml
<CustomObject>
    <label>Data Source</label>
    <nameField>
        <label>Data Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AIDataExtractionCloningController.cls
public with sharing class AIDataExtractionCloningController {
    /**
     * Clones a record identified by the given record ID.
     *
     * This method creates a copy of the record with the specified ID,
     * allowing for duplication of records in the system.
     *
     * @param recordId The unique identifier of the record to be cloned.
     * @return A string indicating the status of the cloning process.
     *         This could be a success message, an error message, or
     *         any relevant information about the cloning operation.
     */
    @AuraEnabled
    public static String cloneRecord(String recordId){
        try{
            return cloneRecord(recordId, null);
        }catch(Exception e){
            GPTfyException.log(e, 'GPTfy', '', 'AIDataExtractionCloningController', 'cloneRecord', '');
            throw new AuraHandledException(e.getMessage());
        }
    }

    //@JIRA : 5031 : Updated cloneRecord method to take input for Data Extraction Mapping Name
    public static String cloneRecord(String recordId, String name){
        AI_Data_Extraction_Mapping__c mapping = [SELECT Id, Name, API_Name__c, Description__c, Object_Name__c, External_Id__c,
                                                 AI_Data_Source__c, Apex_Security_Layer__c
                                                 FROM AI_Data_Extraction_Mapping__c 
                                                 WHERE Id =: recordId 
                                                 LIMIT 1];
        AI_Data_Extraction_Mapping__c cloneMapping = mapping.clone(false, true, false, false);
        //@JIRA : 5031 : Added Data Extraction Mapping Name
        if(String.isNotBlank(name)){
            cloneMapping.Name = name;
        }
        cloneMapping = (AI_Data_Extraction_Mapping__c)FLSCheck.getInstance().insertDML(new List<AI_Data_Extraction_Mapping__c>{cloneMapping}).get(0);            
        
        List<AI_Data_Extraction_Detail__c> extractionDetails = new List<AI_Data_Extraction_Detail__c>();
        Map<String, AI_Data_Extraction_Detail__c> mapMappingDetail = new Map<String, AI_Data_Extraction_Detail__c>();
        for(AI_Data_Extraction_Detail__c mappingDetail : [SELECT AI_Data_Extraction_Mapping__c, Object_Hierarchy__c, Object_Name__c, 
                                                            Parent_Detail__c, RelationshipField__c, RelationshipName__c, Running_Index__c, Type__c, 
                                                            Where_Clause__c, Record_Limit__c, Order_By__c, External_Id__c, Id, Name 
                                                            FROM AI_Data_Extraction_Detail__c 
                                                            WHERE AI_Data_Extraction_Mapping__c =: recordId 
                                                            ORDER BY CreatedDate ASC LIMIT 9999]){
                                                                AI_Data_Extraction_Detail__c cloneMappingDetail = mappingDetail.clone(false, true, false, false);
                                                                cloneMappingDetail.AI_Data_Extraction_Mapping__c = cloneMapping.Id;
                                                                mapMappingDetail.put(mappingDetail.Id, cloneMappingDetail);
                                                            }
        if(!mapMappingDetail.IsEmpty()){
            //FLS enforced via FLSCheck utility using stripInaccessible(AccessType.CREATABLE)
            Map<String, SObject> cleanedRecords = FLSCheck.getInstance().insertDML(mapMappingDetail, true);
            List<SObject> lstDetails = new List<SObject>();
            for(SObject mappingDetail : cleanedRecords.values()){
                if(mappingDetail.get('Parent_Detail__c') != null && cleanedRecords.containsKey((String)mappingDetail.get('Parent_Detail__c'))){
                    mappingDetail.put('Parent_Detail__c', cleanedRecords.get((String)mappingDetail.get('Parent_Detail__c')).Id);
                    lstDetails.add(mappingDetail);
                }
            }
            
            if(lstDetails.size() > 0 && !Test.isRunningTest()){
                FLSCheck.getInstance().updateDML(lstDetails);
            }
        }
        
        List<AI_Data_Extraction_Field__c> extractionFields = new List<AI_Data_Extraction_Field__c>();
        for(AI_Data_Extraction_Field__c field : [SELECT AI_Data_Extraction_Mapping__c, Anonymize_With__c, Field__c, Label__c, Object__c, Scan_for_PII__c, 
                                                 Send_To_AI__c, Type__c, External_Id__c, Field_Type__c, Masking_Scope__c, Id, Name, Formula__c  
                                                 FROM AI_Data_Extraction_Field__c 
                                                 WHERE AI_Data_Extraction_Mapping__c =: recordId ORDER BY CreatedDate ASC LIMIT 9999]){
                                                        AI_Data_Extraction_Field__c cloneExtractionField = field.clone(false, true, false, false);
                                                        cloneExtractionField.AI_Data_Extraction_Mapping__c = cloneMapping.Id;
                                                        extractionFields.add(cloneExtractionField);
                                                    }
        
        if(extractionFields.size()>0){
            FLSCheck.getInstance().insertDML(extractionFields);
        }
        
        return cloneMapping.Id;
    }
}