force-app/main/default/objects/AI_Data_Extraction_Detail__c/AI_Data_Extraction_Detail__c.object-meta.xml
<CustomObject>
    <label>Data Context Detail</label>
    <nameField>
        <label>Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <label>AI Data Extraction Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Object_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Object_Hierarchy__c</fullName>
    <label>Object Hierarchy</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Parent_Detail__c.field-meta.xml
<CustomField>
    <fullName>Parent_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Detail</label>
    <referenceTo>AI_Data_Extraction_Detail__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/AI_Data_Extraction_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Context Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Target Object</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AIDataExtractionDetailTriggerHandler.cls
/**
* @description       : 
* @author            : Rishabh Goel
* @group             : Plumcloud Labs
* @last modified on  : 03-28-2023
* @last modified by  : Rishabh Goel
**/
public with sharing class AIDataExtractionDetailTriggerHandler {
	
    /**
     * This method is called before inserting records of the custom object AI_Data_Extraction_Detail__c.
     * It provides an opportunity to perform any necessary actions or validations
     * before the records are actually inserted into the database.
     *
     * @param newList A list of AI_Data_Extraction_Detail__c objects that are about to be inserted.
     */
    public static void onBeforeInsert(List<AI_Data_Extraction_Detail__c> newList){    
        createObjectHierarchy(newList);
    }
    
    /**
     * This method is called before inserting records of the custom object AI_Data_Extraction_Detail__c.
     * It provides an opportunity to perform any necessary actions or validations
     * before the records are actually inserted into the database.
     *
     * @param newList A list of AI_Data_Extraction_Detail__c objects that are about to be inserted.
     */
    public static void createObjectHierarchy(List<AI_Data_Extraction_Detail__c> newList){
        Set<String> setOfMasterIds = new Set<String>();
        for(AI_Data_Extraction_Detail__c detail : newList){
            setOfMasterIds.add(detail.AI_Data_Extraction_Mapping__c);
        }
        Map<String, AI_Data_Extraction_Mapping__c> mapOfMaster = new Map<String, AI_Data_Extraction_Mapping__c>([
            SELECT Id, Object_Name__c, (SELECT Id, Object_Hierarchy__c FROM AI_Data_Extraction_Details__r) 
            FROM AI_Data_Extraction_Mapping__c WHERE Id IN :setOfMasterIds
        ]);
        Map<String, AI_Data_Extraction_Detail__c> mapOfDetail = new Map<String, AI_Data_Extraction_Detail__c>();
        for(AI_Data_Extraction_Mapping__c master : mapOfMaster.values()){ 
            if(master.AI_Data_Extraction_Details__r != null){
                mapOfDetail.putAll(new Map<String, AI_Data_Extraction_Detail__c>(master.AI_Data_Extraction_Details__r));
            }            
        }
       	
        for(AI_Data_Extraction_Detail__c detail : newList){
            if(detail.Parent_Detail__c == null){
                detail.Object_Hierarchy__c = mapOfMaster.get(detail.AI_Data_Extraction_Mapping__c).Object_Name__c+' > '+detail.Object_Name__c;
            }else if(!mapOfDetail.isEmpty() && mapOfDetail.containsKey(detail.Parent_Detail__c)){
                detail.Object_Hierarchy__c = mapOfDetail.get(detail.Parent_Detail__c).Object_Hierarchy__c+' > '+detail.Object_Name__c;
            }
        }
    }
    
}