force-app/main/default/objects/AI_Data_Extraction_Detail__c/AI_Data_Extraction_Detail__c.object-meta.xml
<CustomObject>
    <label>Data Context Detail</label>
    <nameField>
        <label>Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <label>AI Data Extraction Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <label>Order By</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Parent_Detail__c.field-meta.xml
<CustomField>
    <fullName>Parent_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Detail</label>
    <referenceTo>AI_Data_Extraction_Detail__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/RelationshipField__c.field-meta.xml
<CustomField>
    <fullName>RelationshipField__c</fullName>
    <label>Relationship Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/RelationshipName__c.field-meta.xml
<CustomField>
    <fullName>RelationshipName__c</fullName>
    <label>Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Running_Index__c.field-meta.xml
<CustomField>
    <fullName>Running_Index__c</fullName>
    <label>Running Index</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Detail__c/fields/Where_Clause__c.field-meta.xml
<CustomField>
    <fullName>Where_Clause__c</fullName>
    <inlineHelpText>Where Clause</inlineHelpText>
    <label>Where Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/AI_Data_Extraction_Field__c.object-meta.xml
<CustomObject>
    <label>Data Context Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/AI_Data_Extraction_Mapping__c.field-meta.xml
<CustomField>
    <fullName>AI_Data_Extraction_Mapping__c</fullName>
    <label>AI Data Extraction Mapping</label>
    <referenceTo>AI_Data_Extraction_Mapping__c</referenceTo>
    <relationshipName>AI_Data_Extraction_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Anonymize_With__c.field-meta.xml
<CustomField>
    <fullName>Anonymize_With__c</fullName>
    <label>Anonymize With</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PersonF{n}</fullName>
            </value>
            <value>
                <fullName>PersonL{n}</fullName>
            </value>
            <value>
                <fullName>PersonFull{n}</fullName>
            </value>
            <value>
                <fullName>removed{n}@removed.com</fullName>
            </value>
            <value>
                <fullName>Street{n}</fullName>
            </value>
            <value>
                <fullName>City{n}</fullName>
            </value>
            <value>
                <fullName>State{n}</fullName>
            </value>
            <value>
                <fullName>Country{n}</fullName>
            </value>
            <value>
                <fullName>Phone{n}</fullName>
            </value>
            <value>
                <fullName>Product{n}</fullName>
            </value>
            <value>
                <fullName>Company{n}</fullName>
            </value>
            <value>
                <fullName>{n}</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <label>Formula</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Masking_Scope__c.field-meta.xml
<CustomField>
    <fullName>Masking_Scope__c</fullName>
    <label>Masking Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entire Value</fullName>
            </value>
            <value>
                <fullName>Specific Patterns</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Field__c/fields/Send_To_AI__c.field-meta.xml
<CustomField>
    <fullName>Send_To_AI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send To AI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/AI_Data_Extraction_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Context Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Context Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Data_Extraction_Mapping__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Target Object</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Security_Filters__c/AI_Security_Filters__c.object-meta.xml
<CustomObject>
    <label>Security Layer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Security Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Security_Filters__c/fields/AI_Ignore_Special_Characters__c.field-meta.xml
<CustomField>
    <fullName>AI_Ignore_Special_Characters__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignore Special Characters</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Security_Filters__c/fields/AI_Match_Complete_Word__c.field-meta.xml
<CustomField>
    <fullName>AI_Match_Complete_Word__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Match Complete Word</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AI_Security_Filters__c/fields/AI_Optimized_Search_Pattern__c.field-meta.xml
<CustomField>
    <fullName>AI_Optimized_Search_Pattern__c</fullName>
    <formula>IF( AI_Match_Complete_Word__c ,&quot;(?&lt;=^|\\s)&quot;, &quot;&quot;)&amp;Search_Pattern__c&amp;IF( AI_Match_Complete_Word__c ,&quot;(?=\\s|$)&quot;, &quot;&quot;)</formula>
    <label>Optimized Search Pattern</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Security_Filters__c/fields/Blocklist__c.field-meta.xml
<CustomField>
    <fullName>Blocklist__c</fullName>
    <description>This field is used to house values that will be scanned across long text and rich text fields. If found they will be replaced.</description>
    <inlineHelpText>Separate each value by semi colon.
Example: RX500;DX670;CD245</inlineHelpText>
    <label>Blocklist</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Security_Filters__c/fields/Replacement_Value__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Value__c</fullName>
    <displayFormat>SF-{0000}</displayFormat>
    <inlineHelpText>Ex. Policy{n}</inlineHelpText>
    <label>Replacement Value</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/AI_Security_Filters__c/fields/Search_Pattern__c.field-meta.xml
<CustomField>
    <fullName>Search_Pattern__c</fullName>
    <inlineHelpText>Reguler Expression</inlineHelpText>
    <label>Search Pattern</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AI_Security_Filters__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>National/Tax ID</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Post Code</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Contacts</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>IP/Trade Secrets</fullName>
            </value>
            <value>
                <fullName>Locations</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AIDataExtractionSelector.cls
/**
* @description       : 
* @author            : Rishabh Goel
* @group             : Plumcloud Labs
* @last modified on  : 03-28-2023
* @last modified by  : Rishabh Goel
**/
public with sharing class AIDataExtractionSelector {
    
    STATIC FINAL String STATUS_ACTIVE = 'Active';
    
    static Set<String> getDefaultMappingFields(){
        return new Set<String>{
            'Id',
            'Object_Name__c'
        };
    }

    static Set<String> getDefaultDetailFields(){
        return new Set<String>{
            'Id',
            'AI_Data_Extraction_Mapping__c',
            'Type__c',
            'Running_Index__c',
            'Object_Name__c',
            'Parent_Detail__c',
            'Where_Clause__c',
            'Record_Limit__c',
            'Order_By__c',    
            'RelationshipField__c',
            'RelationshipName__c',
            'Parent_Detail__c',
            'Parent_Detail__r.Object_Name__c',
            'Parent_Detail__r.Where_Clause__c',
            'AI_Data_Extraction_Mapping__r.Object_Name__c',
            'Parent_Detail__r.relationShipField__c'
        };
    }

    static Set<String> getDefaultFields(){
        return new Set<String>{
            'Id',
            'AI_Data_Extraction_Mapping__c',
            'Anonymize_With__c',
            'Field__c',
            'Object__c',
            'Formula__c',
            'Field_Type__c', 
            'Masking_Scope__c',
            'Send_To_AI__c',
            'Type__c',
            'Label__c'
        };
    }
    
    static Set<String> getDefaultSecurityFilterFields(){
        return new Set<String>{
            'Id',
            'Name',
            'Type__c',
            'Search_Pattern__c',
            'Replacement_Value__c',
            'Status__c', 
            'Comment__c',
            'Blocklist__c',
            'RecordTypeId',
            'AI_Ignore_Special_Characters__c',
            'AI_Match_Complete_Word__c',
            'AI_Optimized_Search_Pattern__c'
        };
    }

    public static AI_Data_Extraction_Mapping__c getAIDataExtractionMappingById(Id mappingId){
        List<String> queryFieldList = new List<String>(getDefaultMappingFields());
        String query = 'SELECT ' +String.join(queryFieldList,',') + ' FROM AI_Data_Extraction_Mapping__c WHERE Id=:mappingId LIMIT 1';
        List<AI_Data_Extraction_Mapping__c> extractionMappings = Database.query(query);
        return extractionMappings.isEmpty() ? null : extractionMappings[0];
    }

    public static List<AI_Data_Extraction_Detail__c> getAIDataExtractionDetailByMappingId(Id mappingId){
        List<String> queryFieldList = new List<String>(getDefaultDetailFields());
        String query = 'SELECT ' + String.join(queryFieldList,',') + ' FROM AI_Data_Extraction_Detail__c WHERE AI_Data_Extraction_Mapping__c=:mappingId ORDER BY Running_Index__c ASC';
        return Database.query(query);
    }


    public static List<AI_Data_Extraction_Field__c> getAIDataExtractionFieldsByMappingId(Id mappingId){
        List<String> queryFieldList = new List<String>(getDefaultFields());
        String typeField = 'FIELD';
        // Jira 5988: Security Layer 1 and 2 is conflict
        String query = 'SELECT ' + String.join(queryFieldList,',') + ' FROM AI_Data_Extraction_Field__c WHERE AI_Data_Extraction_Mapping__c=:mappingId AND Type__c =:typeField ORDER BY Anonymize_With__c DESC';
        return Database.query(query);
    }
    
    public static List<AI_Security_Filters__c> getAISecurityFilters(){
        List<String> queryFieldList = new List<String>(getDefaultSecurityFilterFields());
        String query = 'SELECT ' + String.join(queryFieldList,',') + ' FROM AI_Security_Filters__c WHERE Status__c =: STATUS_ACTIVE AND Replacement_Value__c != NULL ';
        return Database.query(query);
    }


}