force-app/main/default/objects/AI_Prompt_Scheduler__c/AI_Prompt_Scheduler__c.object-meta.xml
<CustomObject>
    <label>Prompt Scheduler</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Scheduler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Mapping__c/Request_Mapping__c.object-meta.xml
<CustomObject>
    <label>Request Mapping</label>
    <nameField>
        <label>Request Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Mapping__c/fields/AI_Model__c.field-meta.xml
<CustomField>
    <fullName>AI_Model__c</fullName>
    <label>AI Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OpenAi 3.5-Turbo16K</fullName>
            </value>
            <value>
                <fullName>OpenAi 4.0 Turbo</fullName>
            </value>
            <value>
                <fullName>Google Vertex-Palm-Bison</fullName>
            </value>
            <value>
                <fullName>AWS-Bedrock-CloudeV2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Mapping_Line__c/Request_Mapping_Line__c.object-meta.xml
<CustomObject>
    <label>Request Mapping Line</label>
    <nameField>
        <displayFormat>RML - {00000}</displayFormat>
        <label>Request Mapping Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Mapping Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Mapping_Line__c/fields/Request_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Request_Mapping__c</fullName>
    <label>Request Mapping</label>
    <referenceTo>Request_Mapping__c</referenceTo>
    <relationshipLabel>Request Mapping Lines</relationshipLabel>
    <relationshipName>Request_Mapping_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/reqMappingControllerTest.cls
/**
* @description       : 
* @author            : Sohit Sharma
* @group             : Plumcloud Labs
* @last modified on  : 11-03-2024
* @last modified by  : Sohit Sharma
**/
@isTest
public with sharing class reqMappingControllerTest {
    
    @testSetup
    static void makeData(){
        TestUtility.createRequestMapping('test',true);
    }
    
	@isTest
    public static void getRecords(){
        Request_Mapping__c reqMapping = [Select Id,Name from Request_Mapping__c where Name='test'];
        Test.startTest();
        List<sObject> recList1 = reqMappingController.getRecords(NULL);
        List<sObject> recList2 = reqMappingController.getRecords(reqMapping.Name);
        Test.stopTest();
        System.Assert(recList1 != null);
        System.Assert(recList2 != null);
    }
    
    @isTest
    public static void getFields(){
        String NAMESPACE = reqMappingController.NAMESPACE;
        Test.startTest();
        Map<String, String> mapRec = reqMappingController.getFields(NAMESPACE+'AI_Prompt_Scheduler__c',NAMESPACE+'Scheduler_Related_Fields');
        Test.stopTest();
        System.Assert(mapRec != null); 
    }
    
    @isTest
    public static void createRequestMapping(){
        String NAMESPACE = reqMappingController.NAMESPACE;
      Map<String, Object> reqParams = new Map<String, Object>();
        reqParams.put(NAMESPACE+'Name', 'test2');
        reqParams.put(NAMESPACE+'AI_Model__c', 'OpenAi 3.5-Turbo16K');
        reqParams.put(NAMESPACE+'Description__c', 'test description');
        List<Map<String, Object>> reqLinesList = new List<Map<String, Object>>();
        Map<String, Object> reqLineParams = new Map<String, Object>();
        reqLineParams.put('dataSource', 'Prompt');
        reqLineParams.put('sequence', '1');
        reqLineParams.put('annotation', 'testannotation');
        reqLinesList.add(reqLineParams);
        Test.startTest();
        List<Request_Mapping_Line__c> reqLine = reqMappingController.createRequestMapping(reqParams,reqLinesList);
        Test.stopTest();
        System.Assert(reqLine != null);
    }
}